// Generated by scripts/build-daylog-data.mjs
const dayLogEntries = [
  {
    "date": "2026-04-05",
    "notes": [
      {
        "text": "庭で<em>チェンソーマン</em>を読み終えた。",
        "estimate": {
          "pages": 570,
          "minutes": 90
        }
      },
      {
        "text": "<em>火花</em>を少し読んだ。",
        "estimate": {
          "pages": 77,
          "minutes": 132
        }
      },
      {
        "text": "昼頃に起きた。",
        "estimate": null
      },
      {
        "text": "気分はかなり低く、スティムを使った。",
        "estimate": null
      },
      {
        "text": "2日間漢字をやっていなかったので、追いつくためにやった。",
        "estimate": null
      }
    ],
    "anki": {
      "reviewCount": 133,
      "distinctCards": 127,
      "minutes": 44
    }
  },
  {
    "date": "2026-04-04",
    "notes": [
      {
        "text": "<em>チェンソーマン</em>の13巻から20巻くらいまで読んだ。",
        "estimate": {
          "pages": 1520,
          "minutes": 240
        }
      },
      {
        "text": "Kと飲みに行った。",
        "estimate": null
      }
    ],
    "anki": null
  }
];
