const displayMetadata = {
  "movieDirectors": {
    "lb-https://boxd.it/13Ea": "Paul Weitz",
    "lb-https://boxd.it/14du": "Sofia Coppola",
    "lb-https://boxd.it/15gO": "Byron Howard, Nathan Greno",
    "lb-https://boxd.it/15HA": "Harald Zwart",
    "lb-https://boxd.it/16G4": "Makoto Shinkai",
    "lb-https://boxd.it/16Sk": "Tom McGrath",
    "lb-https://boxd.it/17DK": "Will Gluck",
    "lb-https://boxd.it/17eU": "Michael Haneke",
    "lb-https://boxd.it/17Fc": "Sam Mendes",
    "lb-https://boxd.it/17ue": "David Fincher",
    "lb-https://boxd.it/17uy": "Yoshifumi Kondo",
    "lb-https://boxd.it/18Im": "Mike Nichols",
    "lb-https://boxd.it/18U8": "Peter Weir",
    "lb-https://boxd.it/19Ds": "Yasuhiro Takemoto, Tatsuya Ishihara",
    "lb-https://boxd.it/1A3m": "Drew Barrymore",
    "lb-https://boxd.it/1A40": "Christopher Miller, Phil Lord",
    "lb-https://boxd.it/1a7s": "Bryan Singer",
    "lb-https://boxd.it/1Aq6": "Edgar Wright",
    "lb-https://boxd.it/1au2": "Mike Nichols",
    "lb-https://boxd.it/1BLa": "Bong Joon Ho",
    "lb-https://boxd.it/1BT4": "Mike Leigh",
    "lb-https://boxd.it/1Bv2": "Masaaki Yuasa",
    "lb-https://boxd.it/1CHe": "Hideaki Anno",
    "lb-https://boxd.it/1DD8": "Pierre Coffin, Chris Renaud",
    "lb-https://boxd.it/1DkK": "Yasujirō Ozu",
    "lb-https://boxd.it/1Dsa": "Rajkumar Hirani",
    "lb-https://boxd.it/1dx4": "Tom Ford",
    "lb-https://boxd.it/1E3g": "Robert Bresson",
    "lb-https://boxd.it/1Efm": "James Cameron",
    "lb-https://boxd.it/1Efw": "Karyn Kusama",
    "lb-https://boxd.it/1EmM": "Marc Webb",
    "lb-https://boxd.it/1gB4": "Michael Haneke",
    "lb-https://boxd.it/1GjK": "Todd Phillips",
    "lb-https://boxd.it/1gMc": "Louis Malle",
    "lb-https://boxd.it/1GRM": "Hideaki Anno, Kazuya Tsurumaki",
    "lb-https://boxd.it/1Ha0": "Wong Kar-Wai",
    "lb-https://boxd.it/1HuY": "Yasujirō Ozu",
    "lb-https://boxd.it/1Iik": "Neill Blomkamp",
    "lb-https://boxd.it/1iLA": "Akira Kurosawa",
    "lb-https://boxd.it/1Irc": "Steven Spielberg",
    "lb-https://boxd.it/1j6y": "Andrei Tarkovsky",
    "lb-https://boxd.it/1JAY": "Hayao Miyazaki",
    "lb-https://boxd.it/1Jnq": "Burr Steers",
    "lb-https://boxd.it/1JNS": "Hiroshi Teshigahara",
    "lb-https://boxd.it/1JRg": "Terrence Malick",
    "lb-https://boxd.it/1JTm": "Robert Redford",
    "lb-https://boxd.it/1JTQ": "Greg Mottola",
    "lb-https://boxd.it/1JzG": "Quentin Tarantino",
    "lb-https://boxd.it/1K0C": "Spike Jonze",
    "lb-https://boxd.it/1Kce": "Emeric Pressburger, Michael Powell",
    "lb-https://boxd.it/1M7q": "Ryuichi Hiroki",
    "lb-https://boxd.it/1m9q": "Abbas Kiarostami",
    "lb-https://boxd.it/1MHy": "Harald Zwart",
    "lb-https://boxd.it/1MJk": "John Hughes",
    "lb-https://boxd.it/1MKi": "Kazuya Tsurumaki, Masayuki et al",
    "lb-https://boxd.it/1mky": "Andrzej Wajda",
    "lb-https://boxd.it/1Mn4": "Hayao Miyazaki",
    "lb-https://boxd.it/1Nhm": "Paul Schrader",
    "lb-https://boxd.it/1NhQ": "Henry Selick",
    "lb-https://boxd.it/1nrU": "Ingmar Bergman",
    "lb-https://boxd.it/1NyM": "Kenji Mizoguchi",
    "lb-https://boxd.it/1oDC": "Mamoru Hosoda",
    "lb-https://boxd.it/1OEc": "Pete Docter",
    "lb-https://boxd.it/1OnK": "Errol Morris",
    "lb-https://boxd.it/1OPa": "Mamoru Hosoda",
    "lb-https://boxd.it/1Opc": "Steve James",
    "lb-https://boxd.it/1OUu": "Richard Linklater",
    "lb-https://boxd.it/1PDa": "Wes Anderson",
    "lb-https://boxd.it/1pDe": "Sion Sono",
    "lb-https://boxd.it/1Pui": "Michael Arias",
    "lb-https://boxd.it/1Q6c": "J.J. Abrams",
    "lb-https://boxd.it/1QE4": "Zack Snyder",
    "lb-https://boxd.it/1Qg2": "Satoshi Kon",
    "lb-https://boxd.it/1Qzy": "Clint Eastwood",
    "lb-https://boxd.it/1RFW": "Joel Coen, Ethan Coen",
    "lb-https://boxd.it/1RGA": "Mike Judge",
    "lb-https://boxd.it/1RJE": "Federico Fellini",
    "lb-https://boxd.it/1RkY": "Sion Sono",
    "lb-https://boxd.it/1ROu": "Akira Kurosawa",
    "lb-https://boxd.it/1Row": "Errol Morris",
    "lb-https://boxd.it/1RSc": "Akira Kurosawa",
    "lb-https://boxd.it/1rtq": "Adam McKay",
    "lb-https://boxd.it/1RUM": "Isao Takahata",
    "lb-https://boxd.it/1RYk": "David Yates",
    "lb-https://boxd.it/1RYu": "David Yates",
    "lb-https://boxd.it/1S0A": "Hayao Miyazaki",
    "lb-https://boxd.it/1S3E": "Danny Boyle",
    "lb-https://boxd.it/1sBA": "Paul Schrader",
    "lb-https://boxd.it/1SBw": "Jean-Jacques Beineix",
    "lb-https://boxd.it/1SD8": "Francis Ford Coppola",
    "lb-https://boxd.it/1SDW": "John Musker, Ron Clements",
    "lb-https://boxd.it/1skk": "Christopher Nolan",
    "lb-https://boxd.it/1Sly": "Dave Filoni",
    "lb-https://boxd.it/1SZe": "Jūzō Itami",
    "lb-https://boxd.it/1TAO": "Wes Anderson",
    "lb-https://boxd.it/1tDi": "Terry Zwigoff",
    "lb-https://boxd.it/1TH6": "Ingmar Bergman",
    "lb-https://boxd.it/1Tj4": "Christopher Nolan",
    "lb-https://boxd.it/1TjS": "Guillermo del Toro",
    "lb-https://boxd.it/1TKu": "Roman Polanski",
    "lb-https://boxd.it/1Tlu": "Akira Kurosawa",
    "lb-https://boxd.it/1Tp2": "Hayao Miyazaki",
    "lb-https://boxd.it/1tqo": "Kenji Kodama",
    "lb-https://boxd.it/1TQW": "Roman Polanski",
    "lb-https://boxd.it/1TrW": "Ingmar Bergman",
    "lb-https://boxd.it/1TSo": "Bong Joon Ho",
    "lb-https://boxd.it/1U82": "Martin Scorsese",
    "lb-https://boxd.it/1UDa": "Wong Kar-Wai",
    "lb-https://boxd.it/1ULe": "Martin Scorsese",
    "lb-https://boxd.it/1URc": "Steven Shainberg",
    "lb-https://boxd.it/1V0y": "Kenny Ortega",
    "lb-https://boxd.it/1V8C": "Hamilton Luske, Ben Sharpsteen et al",
    "lb-https://boxd.it/1VCC": "Clyde Geronimi, Wilfred Jackson et al",
    "lb-https://boxd.it/1vCw": "Edward Yang",
    "lb-https://boxd.it/1VEo": "Andrew Stanton",
    "lb-https://boxd.it/1vkW": "Fumihiko Sori",
    "lb-https://boxd.it/1vLe": "Louis Malle",
    "lb-https://boxd.it/1Vmk": "Paul Verhoeven",
    "lb-https://boxd.it/1VNg": "Mark Waters",
    "lb-https://boxd.it/1vsm": "Nobuhiko Obayashi",
    "lb-https://boxd.it/1VZm": "Leon Gast",
    "lb-https://boxd.it/1W2A": "Guy Ritchie",
    "lb-https://boxd.it/1W4G": "Hayao Miyazaki",
    "lb-https://boxd.it/1wBu": "Errol Morris",
    "lb-https://boxd.it/1WKM": "Michael Haneke",
    "lb-https://boxd.it/1WLK": "Jacques Tati",
    "lb-https://boxd.it/1WQU": "Kenneth Branagh",
    "lb-https://boxd.it/1WRe": "Lee Unkrich",
    "lb-https://boxd.it/1WRy": "Dean DeBlois, Chris Sanders",
    "lb-https://boxd.it/1wvm": "Hirokazu Kore-eda",
    "lb-https://boxd.it/1WYO": "John Musker, Ron Clements",
    "lb-https://boxd.it/1WyQ": "Wes Anderson",
    "lb-https://boxd.it/1WZM": "Jon Favreau",
    "lb-https://boxd.it/1xBg": "Andrea Arnold",
    "lb-https://boxd.it/1xFW": "Joss Whedon",
    "lb-https://boxd.it/1XhG": "Gary Trousdale, Kirk Wise",
    "lb-https://boxd.it/1XLm": "Brad Bird",
    "lb-https://boxd.it/1Y2i": "Alfonso Cuarón",
    "lb-https://boxd.it/1YCA": "Robert Clouse",
    "lb-https://boxd.it/1yCu": "Richard Linklater",
    "lb-https://boxd.it/1YEc": "Alexander Payne",
    "lb-https://boxd.it/1Ygk": "Amy Heckerling",
    "lb-https://boxd.it/1YHU": "Wes Anderson",
    "lb-https://boxd.it/1Ylk": "Richard Linklater",
    "lb-https://boxd.it/1YOc": "Jason Reitman",
    "lb-https://boxd.it/1YPY": "John Hughes",
    "lb-https://boxd.it/1YV8": "Werner Herzog",
    "lb-https://boxd.it/1YVC": "Richard Donner",
    "lb-https://boxd.it/1Yw8": "James Foley",
    "lb-https://boxd.it/1Yws": "Mark Osborne, John Stevenson",
    "lb-https://boxd.it/1yx0": "Mike Leigh",
    "lb-https://boxd.it/1YYc": "Mamoru Oshii",
    "lb-https://boxd.it/1Yyy": "John Lasseter",
    "lb-https://boxd.it/1Z6A": "Rian Johnson",
    "lb-https://boxd.it/1zaQ": "Matthew Vaughn",
    "lb-https://boxd.it/1Zdc": "Richard Linklater",
    "lb-https://boxd.it/1ZTM": "Terrence Malick",
    "lb-https://boxd.it/1Zu8": "Terrence Malick",
    "lb-https://boxd.it/1zYm": "Masayuki, Kazuya Tsurumaki et al",
    "lb-https://boxd.it/201Q": "Roger Allers, Rob Minkoff",
    "lb-https://boxd.it/205o": "Andy Tennant",
    "lb-https://boxd.it/20E4": "Paul Thomas Anderson",
    "lb-https://boxd.it/20eA": "Hayao Miyazaki",
    "lb-https://boxd.it/20hO": "Greg Mottola",
    "lb-https://boxd.it/20mu": "Alejandro Jodorowsky",
    "lb-https://boxd.it/20n8": "Martin McDonagh",
    "lb-https://boxd.it/20pI": "Olivier Assayas",
    "lb-https://boxd.it/20QY": "Karey Kirkpatrick, Tim Johnson",
    "lb-https://boxd.it/20RW": "Mike Judge",
    "lb-https://boxd.it/20UQ": "Lana Wachowski, Lilly Wachowski",
    "lb-https://boxd.it/20wu": "Jared Hess",
    "lb-https://boxd.it/20Z2": "Paul Thomas Anderson",
    "lb-https://boxd.it/210a": "Jason Reitman",
    "lb-https://boxd.it/21ew": "Joel Coen, Ethan Coen",
    "lb-https://boxd.it/22Vw": "Simon J. Smith, Steve Hickner",
    "lb-https://boxd.it/22WY": "Alain Resnais",
    "lb-https://boxd.it/22yC": "Satyajit Ray",
    "lb-https://boxd.it/23BW": "Ethan Coen, Joel Coen",
    "lb-https://boxd.it/23De": "Hayao Miyazaki",
    "lb-https://boxd.it/23um": "Paul Thomas Anderson",
    "lb-https://boxd.it/23wW": "Satoshi Kon",
    "lb-https://boxd.it/23zw": "Charlie Kaufman",
    "lb-https://boxd.it/248G": "Park Chan-wook",
    "lb-https://boxd.it/24QS": "Trey Parker",
    "lb-https://boxd.it/251c": "Akira Kurosawa",
    "lb-https://boxd.it/252a": "Kaneto Shindō",
    "lb-https://boxd.it/25A2": "Stanley Kubrick",
    "lb-https://boxd.it/25AQ": "David Hand",
    "lb-https://boxd.it/25Fm": "Terrence Malick",
    "lb-https://boxd.it/25jK": "Richard Linklater",
    "lb-https://boxd.it/25zo": "Mike Judge",
    "lb-https://boxd.it/25zS": "Kinji Fukasaku",
    "lb-https://boxd.it/26AM": "Louis Malle",
    "lb-https://boxd.it/26Co": "Louis Malle",
    "lb-https://boxd.it/26E0": "Hirokazu Kore-eda",
    "lb-https://boxd.it/26EO": "Doug Liman",
    "lb-https://boxd.it/26EY": "Rob Reiner",
    "lb-https://boxd.it/26j2": "Jean-Luc Godard",
    "lb-https://boxd.it/26l8": "Paul Schrader",
    "lb-https://boxd.it/26mA": "Spike Jonze",
    "lb-https://boxd.it/26x4": "Michael Lehmann",
    "lb-https://boxd.it/27Hk": "Michael Haneke",
    "lb-https://boxd.it/27PI": "Marc Webb",
    "lb-https://boxd.it/27q4": "John Hughes",
    "lb-https://boxd.it/27qy": "Paul Weitz",
    "lb-https://boxd.it/27US": "George Lucas",
    "lb-https://boxd.it/27V2": "George Lucas",
    "lb-https://boxd.it/27Vc": "George Lucas",
    "lb-https://boxd.it/27Vm": "Richard Marquand",
    "lb-https://boxd.it/27Vw": "Irvin Kershner",
    "lb-https://boxd.it/27Wa": "Sofia Coppola",
    "lb-https://boxd.it/27Wk": "John G. Avildsen",
    "lb-https://boxd.it/27ww": "Brad Bird",
    "lb-https://boxd.it/287i": "Gus Van Sant",
    "lb-https://boxd.it/2886": "Michael Haneke",
    "lb-https://boxd.it/28a2": "Michael Moore",
    "lb-https://boxd.it/28b0": "Joe Johnston",
    "lb-https://boxd.it/28Bs": "Robert Bresson",
    "lb-https://boxd.it/28dA": "Jon Favreau",
    "lb-https://boxd.it/28Dy": "Terry Zwigoff",
    "lb-https://boxd.it/28Em": "Mike Judge",
    "lb-https://boxd.it/28JG": "Sofia Coppola",
    "lb-https://boxd.it/28kc": "Ishirō Honda",
    "lb-https://boxd.it/28Ls": "Michael Moore",
    "lb-https://boxd.it/28MA": "Martin Scorsese",
    "lb-https://boxd.it/28No": "Guillermo del Toro",
    "lb-https://boxd.it/28PO": "Andrei Tarkovsky",
    "lb-https://boxd.it/28Q8": "Andrei Tarkovsky",
    "lb-https://boxd.it/28rC": "Jean-Luc Godard",
    "lb-https://boxd.it/28Uk": "John G. Avildsen",
    "lb-https://boxd.it/28Vs": "Mary Harron",
    "lb-https://boxd.it/28xA": "Frank Capra",
    "lb-https://boxd.it/28xK": "Richard Linklater",
    "lb-https://boxd.it/28yI": "Martin Scorsese",
    "lb-https://boxd.it/28yo": "Alfred Hitchcock",
    "lb-https://boxd.it/28ZY": "Bong Joon Ho",
    "lb-https://boxd.it/290C": "Clint Eastwood",
    "lb-https://boxd.it/292o": "Alejandro González Iñárritu",
    "lb-https://boxd.it/293w": "Christopher Nolan",
    "lb-https://boxd.it/297I": "Billy Wilder",
    "lb-https://boxd.it/297o": "David Lynch",
    "lb-https://boxd.it/299u": "David Lynch",
    "lb-https://boxd.it/29B4": "Ingmar Bergman",
    "lb-https://boxd.it/29BI": "David Lynch",
    "lb-https://boxd.it/29dc": "Eric Darnell, Tom McGrath",
    "lb-https://boxd.it/29Du": "Andrew Niccol",
    "lb-https://boxd.it/29EW": "Jonathan Dayton, Valerie Faris",
    "lb-https://boxd.it/29eY": "Stanley Kubrick",
    "lb-https://boxd.it/29FA": "Martin Scorsese",
    "lb-https://boxd.it/29Fg": "Chris Columbus",
    "lb-https://boxd.it/29Fq": "Victor Fleming",
    "lb-https://boxd.it/29FU": "David Yates",
    "lb-https://boxd.it/29GI": "Terry Gilliam, Terry Jones",
    "lb-https://boxd.it/29HG": "Samuel Armstrong, James Algar et al",
    "lb-https://boxd.it/29ho": "John Lasseter",
    "lb-https://boxd.it/29lU": "Alan J. Pakula",
    "lb-https://boxd.it/29M2": "Woody Allen",
    "lb-https://boxd.it/29Na": "Woody Allen",
    "lb-https://boxd.it/29Nu": "Stanley Kubrick",
    "lb-https://boxd.it/29O8": "Robert Bresson",
    "lb-https://boxd.it/29Pq": "Quentin Tarantino",
    "lb-https://boxd.it/29qA": "John Lasseter",
    "lb-https://boxd.it/29Qe": "David Yates",
    "lb-https://boxd.it/29QI": "Chris Columbus",
    "lb-https://boxd.it/29Qo": "Mike Newell",
    "lb-https://boxd.it/29qq": "John Lasseter",
    "lb-https://boxd.it/29QS": "Chris Columbus",
    "lb-https://boxd.it/29qU": "John Badham",
    "lb-https://boxd.it/29Qy": "Alfonso Cuarón",
    "lb-https://boxd.it/29R2": "Park Chan-wook",
    "lb-https://boxd.it/29RQ": "William Wyler",
    "lb-https://boxd.it/29ry": "Robert Zemeckis",
    "lb-https://boxd.it/29tE": "Wong Kar-Wai",
    "lb-https://boxd.it/29Ts": "Wim Wenders",
    "lb-https://boxd.it/29Uq": "Luis Buñuel",
    "lb-https://boxd.it/29VI": "Darren Aronofsky",
    "lb-https://boxd.it/29VS": "Steven Spielberg",
    "lb-https://boxd.it/29vU": "Roman Polanski",
    "lb-https://boxd.it/29Xu": "Victor Fleming",
    "lb-https://boxd.it/29z8": "Conrad Vernon, Kelly Asbury et al",
    "lb-https://boxd.it/29ZA": "Edward Zwick",
    "lb-https://boxd.it/29zi": "Andrew Adamson, Vicky Jenson",
    "lb-https://boxd.it/29ZK": "Mel Gibson",
    "lb-https://boxd.it/29zM": "Roman Polanski",
    "lb-https://boxd.it/29ZU": "Ingmar Bergman",
    "lb-https://boxd.it/29zW": "William Wyler",
    "lb-https://boxd.it/2a0I": "Barry Sonnenfeld",
    "lb-https://boxd.it/2a1G": "Steven Spielberg",
    "lb-https://boxd.it/2a1m": "Lana Wachowski, Lilly Wachowski",
    "lb-https://boxd.it/2a1Q": "Stanley Kubrick",
    "lb-https://boxd.it/2a20": "Billy Wilder",
    "lb-https://boxd.it/2a2k": "James Cameron",
    "lb-https://boxd.it/2a2Y": "Andrei Tarkovsky",
    "lb-https://boxd.it/2a3s": "Stephen Daldry",
    "lb-https://boxd.it/2a46": "Pete Docter",
    "lb-https://boxd.it/2a4A": "Florian Henckel von Donnersmarck",
    "lb-https://boxd.it/2a5e": "Steven Spielberg",
    "lb-https://boxd.it/2a5o": "Gus Van Sant",
    "lb-https://boxd.it/2a6m": "Alfred Hitchcock",
    "lb-https://boxd.it/2a6Q": "Alfred Hitchcock",
    "lb-https://boxd.it/2a7k": "Paul Verhoeven",
    "lb-https://boxd.it/2a7u": "John McTiernan",
    "lb-https://boxd.it/2a7Y": "Sam Raimi",
    "lb-https://boxd.it/2a88": "Sam Raimi",
    "lb-https://boxd.it/2a8i": "Sam Raimi",
    "lb-https://boxd.it/2a8W": "Lars von Trier",
    "lb-https://boxd.it/2a9K": "Akira Kurosawa",
    "lb-https://boxd.it/2a9q": "David Fincher",
    "lb-https://boxd.it/2aA2": "Steven Spielberg",
    "lb-https://boxd.it/2aae": "Bobby Farrelly, Peter Farrelly",
    "lb-https://boxd.it/2aAG": "Clint Eastwood",
    "lb-https://boxd.it/2aB0": "Christopher Nolan",
    "lb-https://boxd.it/2ab2": "Alfred Hitchcock",
    "lb-https://boxd.it/2aeA": "Miloš Forman",
    "lb-https://boxd.it/2aFQ": "Joel Coen",
    "lb-https://boxd.it/2aG0": "Michael Curtiz",
    "lb-https://boxd.it/2agc": "Quentin Tarantino",
    "lb-https://boxd.it/2aGE": "Billy Wilder",
    "lb-https://boxd.it/2agQ": "Larry Charles",
    "lb-https://boxd.it/2aH8": "Miloš Forman",
    "lb-https://boxd.it/2aHi": "Frank Darabont",
    "lb-https://boxd.it/2aHM": "Joel Coen",
    "lb-https://boxd.it/2ahu": "Spike Jonze",
    "lb-https://boxd.it/2aHW": "Jonathan Demme",
    "lb-https://boxd.it/2ahY": "Gus Van Sant",
    "lb-https://boxd.it/2aIg": "Christopher Nolan",
    "lb-https://boxd.it/2ajq": "Darren Aronofsky",
    "lb-https://boxd.it/2aMi": "Stanley Kubrick",
    "lb-https://boxd.it/2amk": "Ron Howard",
    "lb-https://boxd.it/2aMW": "Stephen Frears",
    "lb-https://boxd.it/2amY": "Michael Haneke",
    "lb-https://boxd.it/2anC": "Federico Fellini",
    "lb-https://boxd.it/2aNK": "Francis Ford Coppola",
    "lb-https://boxd.it/2aNq": "Francis Ford Coppola",
    "lb-https://boxd.it/2aOe": "Rob Reiner",
    "lb-https://boxd.it/2apI": "Alfred Hitchcock",
    "lb-https://boxd.it/2aPw": "Francis Ford Coppola",
    "lb-https://boxd.it/2aq2": "Steven Spielberg",
    "lb-https://boxd.it/2aqc": "Roman Polanski",
    "lb-https://boxd.it/2aqm": "Federico Fellini",
    "lb-https://boxd.it/2aRM": "Alfred Hitchcock",
    "lb-https://boxd.it/2arO": "David Hand, Ben Sharpsteen et al",
    "lb-https://boxd.it/2aSg": "Peter Weir",
    "lb-https://boxd.it/2asM": "Paul Verhoeven",
    "lb-https://boxd.it/2aTI": "Mel Gibson",
    "lb-https://boxd.it/2aTS": "Robert Zemeckis",
    "lb-https://boxd.it/2au4": "Quentin Tarantino",
    "lb-https://boxd.it/2aUc": "Jean-Pierre Jeunet",
    "lb-https://boxd.it/2auI": "Sidney Lumet",
    "lb-https://boxd.it/2aVE": "Stanley Kubrick",
    "lb-https://boxd.it/2aVO": "Quentin Tarantino",
    "lb-https://boxd.it/2awE": "David Frankel",
    "lb-https://boxd.it/2AwK": "Michel Hazanavicius",
    "lb-https://boxd.it/2awY": "Ridley Scott",
    "lb-https://boxd.it/2axi": "Akira Kurosawa",
    "lb-https://boxd.it/2axs": "Stanley Kubrick",
    "lb-https://boxd.it/2aYI": "Robert Zemeckis",
    "lb-https://boxd.it/2aYS": "Blake Edwards",
    "lb-https://boxd.it/2aZc": "Tim Burton",
    "lb-https://boxd.it/2aze": "Paul Thomas Anderson",
    "lb-https://boxd.it/2aZm": "Steven Soderbergh",
    "lb-https://boxd.it/2b0E": "Sofia Coppola",
    "lb-https://boxd.it/2b0k": "Christopher Nolan",
    "lb-https://boxd.it/2b1C": "François Truffaut",
    "lb-https://boxd.it/2b1i": "Katsuhiro Otomo",
    "lb-https://boxd.it/2b1W": "Lars von Trier",
    "lb-https://boxd.it/2b3e": "Harold Ramis",
    "lb-https://boxd.it/2b3I": "Joel Coen",
    "lb-https://boxd.it/2b4m": "Hayao Miyazaki",
    "lb-https://boxd.it/2b4w": "Hayao Miyazaki",
    "lb-https://boxd.it/2b5E": "Peter Jackson",
    "lb-https://boxd.it/2b5O": "Peter Jackson",
    "lb-https://boxd.it/2b5u": "Peter Jackson",
    "lb-https://boxd.it/2b68": "Tim Burton",
    "lb-https://boxd.it/2b6C": "Joel Coen",
    "lb-https://boxd.it/2b6M": "Garry Marshall",
    "lb-https://boxd.it/2b7A": "Krzysztof Kieślowski",
    "lb-https://boxd.it/2b7K": "Krzysztof Kieślowski",
    "lb-https://boxd.it/2b8e": "Robert Zemeckis",
    "lb-https://boxd.it/2b8y": "Martin Scorsese",
    "lb-https://boxd.it/2b9m": "Ridley Scott",
    "lb-https://boxd.it/2bb8": "Steven Spielberg",
    "lb-https://boxd.it/2bbs": "Steven Spielberg",
    "lb-https://boxd.it/2bc6": "Hayao Miyazaki",
    "lb-https://boxd.it/2bcA": "Ridley Scott",
    "lb-https://boxd.it/2bcg": "Richard Linklater",
    "lb-https://boxd.it/2bcK": "Christopher Nolan",
    "lb-https://boxd.it/2bcU": "Richard Linklater",
    "lb-https://boxd.it/2bdI": "Clint Eastwood",
    "lb-https://boxd.it/2bew": "Curtis Hanson",
    "lb-https://boxd.it/2bf0": "Stanley Kubrick",
    "lb-https://boxd.it/2bfk": "Gore Verbinski",
    "lb-https://boxd.it/2Bsu": "Louis Leterrier",
    "lb-https://boxd.it/2BwG": "Hideaki Anno, Masayuki et al",
    "lb-https://boxd.it/2cAo": "Martin Scorsese",
    "lb-https://boxd.it/2cB2": "Guillermo del Toro",
    "lb-https://boxd.it/2cBG": "Paul Thomas Anderson",
    "lb-https://boxd.it/2cBQ": "Shane Black",
    "lb-https://boxd.it/2cCk": "Quentin Tarantino",
    "lb-https://boxd.it/2CxU": "Steve McQueen",
    "lb-https://boxd.it/2czU": "Ben Affleck",
    "lb-https://boxd.it/2D2e": "Steve McQueen",
    "lb-https://boxd.it/2DjO": "George Miller",
    "lb-https://boxd.it/2DqA": "Alan Taylor",
    "lb-https://boxd.it/2DyE": "Wim Wenders",
    "lb-https://boxd.it/2L3k": "Hirokazu Kore-eda",
    "lb-https://boxd.it/2lkk": "Yasujirō Ozu",
    "lb-https://boxd.it/2n2s": "Steven Spielberg",
    "lb-https://boxd.it/2oFK": "Alastair Fothergill, Mark Linfield",
    "lb-https://boxd.it/2peU": "Roman Polanski",
    "lb-https://boxd.it/2pgc": "Seth MacFarlane",
    "lb-https://boxd.it/2pZ2": "Yukio Mishima",
    "lb-https://boxd.it/2s9e": "Ridley Scott",
    "lb-https://boxd.it/2sv0": "Hideaki Anno",
    "lb-https://boxd.it/2TT4": "Tom Hooper",
    "lb-https://boxd.it/2TTo": "David O. Russell",
    "lb-https://boxd.it/2TTS": "Rich Moore",
    "lb-https://boxd.it/2uds": "Gary Ross",
    "lb-https://boxd.it/2VCa": "Goro Miyazaki",
    "lb-https://boxd.it/2W7s": "James Cameron",
    "lb-https://boxd.it/2Wng": "Wes Anderson",
    "lb-https://boxd.it/2ZA8": "Stephen Chbosky",
    "lb-https://boxd.it/3178": "Richard Linklater",
    "lb-https://boxd.it/34Q6": "Michael Haneke",
    "lb-https://boxd.it/34Qq": "Terrence Malick",
    "lb-https://boxd.it/34Ro": "Ethan Coen, Joel Coen",
    "lb-https://boxd.it/36qO": "Terry Zwigoff",
    "lb-https://boxd.it/37pC": "Ang Lee",
    "lb-https://boxd.it/3C1m": "Martin Scorsese",
    "lb-https://boxd.it/3eWe": "Richard Linklater",
    "lb-https://boxd.it/3GNa": "Jennifer Lee, Chris Buck",
    "lb-https://boxd.it/3Hbw": "Paul Schrader",
    "lb-https://boxd.it/3Icg": "Bong Joon Ho",
    "lb-https://boxd.it/3Ipk": "Mamoru Hosoda",
    "lb-https://boxd.it/3lPY": "Sofia Coppola",
    "lb-https://boxd.it/3OsE": "Jason Moore",
    "lb-https://boxd.it/3q1k": "Hiroshi Ando",
    "lb-https://boxd.it/3qi6": "Joss Whedon",
    "lb-https://boxd.it/3r58": "Joe Russo, Anthony Russo",
    "lb-https://boxd.it/3sAw": "Francis Lawrence",
    "lb-https://boxd.it/3SWy": "Ben Stiller",
    "lb-https://boxd.it/3utM": "Marc Webb",
    "lb-https://boxd.it/3VH2": "James Gunn",
    "lb-https://boxd.it/3ZqO": "Wes Anderson",
    "lb-https://boxd.it/41Xg": "Noah Baumbach",
    "lb-https://boxd.it/421s": "Harmony Korine",
    "lb-https://boxd.it/43aU": "Peter Jackson",
    "lb-https://boxd.it/44Cg": "Joshua Oppenheimer",
    "lb-https://boxd.it/477U": "Lena Dunham",
    "lb-https://boxd.it/493A": "Vincent Patar, Stéphane Aubier et al",
    "lb-https://boxd.it/4aAA": "Andrew Stanton",
    "lb-https://boxd.it/4aRw": "Bryan Singer",
    "lb-https://boxd.it/4BjQ": "Paul Weitz",
    "lb-https://boxd.it/4cWo": "Niki Lindroth von Bahr",
    "lb-https://boxd.it/4hka": "Francis Lawrence",
    "lb-https://boxd.it/4ive": "Richard Linklater",
    "lb-https://boxd.it/4JQI": "Isao Takahata",
    "lb-https://boxd.it/4JQS": "Hayao Miyazaki",
    "lb-https://boxd.it/4KHC": "Pete Docter",
    "lb-https://boxd.it/4O24": "Spike Jonze",
    "lb-https://boxd.it/4O40": "Abdellatif Kechiche",
    "lb-https://boxd.it/4pD0": "Doug Liman",
    "lb-https://boxd.it/4pDO": "Phil Lord, Christopher Miller",
    "lb-https://boxd.it/4srQ": "Rawson Marshall Thurber",
    "lb-https://boxd.it/4UG": "Keiichi Hara",
    "lb-https://boxd.it/4vru": "J.J. Abrams",
    "lb-https://boxd.it/4VSG": "James Ponsoldt",
    "lb-https://boxd.it/4VZ8": "Christopher Nolan",
    "lb-https://boxd.it/50MI": "Woody Allen",
    "lb-https://boxd.it/5dz8": "David O. Russell",
    "lb-https://boxd.it/5Fvy": "Phil Lord, Christopher Miller",
    "lb-https://boxd.it/5Ik4": "Justin Lin",
    "lb-https://boxd.it/5LDy": "Clint Eastwood",
    "lb-https://boxd.it/5MP6": "Frank Pavich",
    "lb-https://boxd.it/5nry": "Daihachi Yoshida",
    "lb-https://boxd.it/5RFA": "Alejandro González Iñárritu",
    "lb-https://boxd.it/5rQs": "Hirokazu Kore-eda",
    "lb-https://boxd.it/5Txe": "Nicholas Stoller",
    "lb-https://boxd.it/5xlK": "J.J. Abrams",
    "lb-https://boxd.it/5xme": "Rian Johnson",
    "lb-https://boxd.it/5Ymq": "Makoto Shinkai",
    "lb-https://boxd.it/6aig": "Morten Tyldum",
    "lb-https://boxd.it/6dxe": "Matthew Vaughn",
    "lb-https://boxd.it/6ehm": "David Wnendt",
    "lb-https://boxd.it/6fBW": "Zack Snyder",
    "lb-https://boxd.it/6hQu": "David Fincher",
    "lb-https://boxd.it/6YK": "Michel Gondry",
    "lb-https://boxd.it/6Z4": "Clint Eastwood",
    "lb-https://boxd.it/6ZS": "Francis Ford Coppola",
    "lb-https://boxd.it/70G": "Gore Verbinski",
    "lb-https://boxd.it/70w": "Quentin Tarantino",
    "lb-https://boxd.it/71a": "Fritz Lang",
    "lb-https://boxd.it/71Y": "Sam Mendes",
    "lb-https://boxd.it/728": "Robert Zemeckis",
    "lb-https://boxd.it/72i": "Andrew Stanton",
    "lb-https://boxd.it/72s": "George Lucas",
    "lb-https://boxd.it/780m": "Dan Gilroy",
    "lb-https://boxd.it/78pm": "Hiromasa Yonebayashi",
    "lb-https://boxd.it/7bQA": "Damien Chazelle",
    "lb-https://boxd.it/7eJi": "Bryan Singer",
    "lb-https://boxd.it/7f62": "Olivier Assayas",
    "lb-https://boxd.it/7FPC": "David Yates",
    "lb-https://boxd.it/7IPg": "Brad Bird",
    "lb-https://boxd.it/7jIE": "James Ponsoldt",
    "lb-https://boxd.it/7miO": "Nobuhiro Yamashita",
    "lb-https://boxd.it/7oOi": "Mami Sunada",
    "lb-https://boxd.it/7Piy": "James Mangold",
    "lb-https://boxd.it/7SuC": "Ken Iizuka",
    "lb-https://boxd.it/7T2k": "Alex Garland",
    "lb-https://boxd.it/7tnw": "Yorgos Lanthimos",
    "lb-https://boxd.it/7Ua0": "Nuri Bilge Ceylan",
    "lb-https://boxd.it/7UcA": "Ruben Östlund",
    "lb-https://boxd.it/7Xv6": "Zatella Beatty",
    "lb-https://boxd.it/84xS": "Byron Howard, Rich Moore",
    "lb-https://boxd.it/87wo": "David Robert Mitchell",
    "lb-https://boxd.it/8F44": "Cho Beom-gu",
    "lb-https://boxd.it/8JOq": "Woody Allen",
    "lb-https://boxd.it/8LnQ": "Katsuichi Nakayama, Kazuya Tsurumaki et al",
    "lb-https://boxd.it/8MHi": "Taika Waititi",
    "lb-https://boxd.it/8MHs": "Ryan Coogler",
    "lb-https://boxd.it/8SeG": "Ridley Scott",
    "lb-https://boxd.it/8Vtu": "Ryuichi Hiroki",
    "lb-https://boxd.it/948A": "Park Chan-wook",
    "lb-https://boxd.it/97TE": "Duke Johnson, Charlie Kaufman",
    "lb-https://boxd.it/9fOC": "Tim Miller",
    "lb-https://boxd.it/9Gr6": "Don Hertzfeldt",
    "lb-https://boxd.it/9HRY": "Niki Lindroth von Bahr",
    "lb-https://boxd.it/9mgM": "Richard Linklater",
    "lb-https://boxd.it/9Phu": "Antoine Fuqua",
    "lb-https://boxd.it/9roG": "Patty Jenkins",
    "lb-https://boxd.it/9SAE": "Alfonso Gomez-Rejon",
    "lb-https://boxd.it/9Tho": "Rick Famuyiwa",
    "lb-https://boxd.it/9vE4": "Joe Russo, Anthony Russo",
    "lb-https://boxd.it/9vEe": "Joe Russo, Anthony Russo",
    "lb-https://boxd.it/9vSA": "Ryan Fleck, Anna Boden",
    "lb-https://boxd.it/9X0m": "Robert Eggers",
    "lb-https://boxd.it/a2qk": "Ryan Coogler",
    "lb-https://boxd.it/a5fa": "Damien Chazelle",
    "lb-https://boxd.it/a84k": "Tom McCarthy",
    "lb-https://boxd.it/aA80": "Nicholas Stoller",
    "lb-https://boxd.it/abBm": "Hirokazu Kore-eda",
    "lb-https://boxd.it/aboM": "Jon Watts",
    "lb-https://boxd.it/AF4": "Hiromasa Yonebayashi",
    "lb-https://boxd.it/ajZw": "Adam McKay",
    "lb-https://boxd.it/alaK": "Naomi Kawase",
    "lb-https://boxd.it/AmDK": "Shunsuke Kariyama",
    "lb-https://boxd.it/aNGk": "Denis Villeneuve",
    "lb-https://boxd.it/aPvy": "Gareth Edwards",
    "lb-https://boxd.it/Arw0": "Charlotte Wells",
    "lb-https://boxd.it/aSVk": "Greta Gerwig",
    "lb-https://boxd.it/ATh8": "Wim Wenders",
    "lb-https://boxd.it/aXgc": "Bradley Cooper",
    "lb-https://boxd.it/aZes": "Steven Spielberg",
    "lb-https://boxd.it/azpY": "Bob Persichetti, Peter Ramsey et al",
    "lb-https://boxd.it/b2L0": "Kenneth Lonergan",
    "lb-https://boxd.it/b8wK": "Denis Villeneuve",
    "lb-https://boxd.it/B9dw": "Louis C.K.",
    "lb-https://boxd.it/bC8e": "Andy Muschietti",
    "lb-https://boxd.it/bCLK": "Greta Gerwig",
    "lb-https://boxd.it/bdhq": "Paul Verhoeven",
    "lb-https://boxd.it/bGWs": "Ron Howard",
    "lb-https://boxd.it/bhF2": "Edgar Wright",
    "lb-https://boxd.it/bjvI": "Sion Sono",
    "lb-https://boxd.it/bJVW": "Nobuhiro Doi",
    "lb-https://boxd.it/bk7C": "Andrea Arnold",
    "lb-https://boxd.it/bkGM": "Olivier Assayas",
    "lb-https://boxd.it/bPI": "Lars von Trier",
    "lb-https://boxd.it/bQiC": "Michael Moore",
    "lb-https://boxd.it/bSVc": "Christopher McQuarrie",
    "lb-https://boxd.it/bVG": "Mark Andrews, Brenda Chapman",
    "lb-https://boxd.it/Bz3C": "Andrew Haigh",
    "lb-https://boxd.it/cdzQ": "Doug Liman",
    "lb-https://boxd.it/cHxg": "Cassie Jaye",
    "lb-https://boxd.it/cjr4": "Joseph Kosinski",
    "lb-https://boxd.it/CKrM": "Rikiya Imaizumi",
    "lb-https://boxd.it/cUqs": "Makoto Shinkai",
    "lb-https://boxd.it/CUU": "Yasujirō Ozu",
    "lb-https://boxd.it/d0HY": "Hirokazu Kore-eda",
    "lb-https://boxd.it/d0vI": "Cristian Mungiu",
    "lb-https://boxd.it/d0Y6": "Christopher Nolan",
    "lb-https://boxd.it/d2we": "Asghar Farhadi",
    "lb-https://boxd.it/d5nu": "Kelly Fremon Craig",
    "lb-https://boxd.it/d6bE": "Barry Jenkins",
    "lb-https://boxd.it/D7Co": "Yusaku Matsumoto",
    "lb-https://boxd.it/d99c": "Naoko Yamada",
    "lb-https://boxd.it/dGNE": "Greta Gerwig",
    "lb-https://boxd.it/dj9c": "Shunji Iwai",
    "lb-https://boxd.it/DJEM": "Hirokazu Kore-eda",
    "lb-https://boxd.it/dlLM": "David Leitch",
    "lb-https://boxd.it/dMG0": "Sean Baker",
    "lb-https://boxd.it/Doq": "Dennis Dugan",
    "lb-https://boxd.it/dSl8": "Aaron Sorkin",
    "lb-https://boxd.it/DUHM": "Paul Thomas Anderson",
    "lb-https://boxd.it/dVHQ": "Cory Finley",
    "lb-https://boxd.it/dVI": "J.J. Abrams",
    "lb-https://boxd.it/dX0": "Tom Hooper",
    "lb-https://boxd.it/dYmm": "Luca Guadagnino",
    "lb-https://boxd.it/dYOq": "Martin Scorsese",
    "lb-https://boxd.it/dZ5G": "Yorgos Lanthimos",
    "lb-https://boxd.it/dZ5m": "Guillermo del Toro",
    "lb-https://boxd.it/dzR0": "Craig Gillespie",
    "lb-https://boxd.it/dZrW": "Wes Anderson",
    "lb-https://boxd.it/E4G": "Yasujirō Ozu",
    "lb-https://boxd.it/e4uc": "Paul Thomas Anderson",
    "lb-https://boxd.it/e5YW": "Ruben Östlund",
    "lb-https://boxd.it/ea9Y": "Armando Iannucci",
    "lb-https://boxd.it/eCuA": "Kogonada",
    "lb-https://boxd.it/eDGs": "Matt Reeves",
    "lb-https://boxd.it/Egcw": "Sean Baker",
    "lb-https://boxd.it/EMTM": "Zach Cregger",
    "lb-https://boxd.it/EMy": "Terence Davies",
    "lb-https://boxd.it/eOCm": "Jordan Peele",
    "lb-https://boxd.it/f1TK": "Bryan Singer",
    "lb-https://boxd.it/f21E": "Boots Riley",
    "lb-https://boxd.it/f42u": "Macon Blair",
    "lb-https://boxd.it/f69M": "Alfonso Cuarón",
    "lb-https://boxd.it/fA7G": "Denis Villeneuve",
    "lb-https://boxd.it/fb0K": "David Lowery",
    "lb-https://boxd.it/ffwA": "Masaaki Yuasa",
    "lb-https://boxd.it/fmje": "Bryan Fogel",
    "lb-https://boxd.it/FOA": "Matthew Vaughn",
    "lb-https://boxd.it/fQ7W": "Marc Meyers",
    "lb-https://boxd.it/fqF4": "Hirokazu Kore-eda",
    "lb-https://boxd.it/FRk": "Zack Snyder",
    "lb-https://boxd.it/FSts": "Shinnosuke Yakuwa",
    "lb-https://boxd.it/ft3W": "Kazuya Shiraishi",
    "lb-https://boxd.it/fVA0": "Rob Letterman",
    "lb-https://boxd.it/fVJQ": "John Krasinski",
    "lb-https://boxd.it/fYde": "Jean-Marc Vallée",
    "lb-https://boxd.it/g02s": "Greg Berlanti",
    "lb-https://boxd.it/g0rM": "Daihachi Yoshida",
    "lb-https://boxd.it/g2w": "Ivan Reitman",
    "lb-https://boxd.it/gfnK": "Jon M. Chu",
    "lb-https://boxd.it/ggpM": "Nattawut Poonpiriya",
    "lb-https://boxd.it/gH0O": "Quentin Tarantino",
    "lb-https://boxd.it/ghHs": "Andrew Bujalski",
    "lb-https://boxd.it/gJsA": "Jonathan Glazer",
    "lb-https://boxd.it/gkhM": "Niki Lindroth von Bahr",
    "lb-https://boxd.it/glS": "Bennett Miller",
    "lb-https://boxd.it/go9C": "Paul Schrader",
    "lb-https://boxd.it/gpVi": "Hiroshi Nishitani",
    "lb-https://boxd.it/gvo": "Asghar Farhadi",
    "lb-https://boxd.it/GZk": "Peter Jackson",
    "lb-https://boxd.it/GZY": "Alfonso Cuarón",
    "lb-https://boxd.it/h0ZQ": "Charles Stone III",
    "lb-https://boxd.it/H3m": "Christopher Nolan",
    "lb-https://boxd.it/h4cS": "Todd Phillips",
    "lb-https://boxd.it/H4Y": "John Lasseter",
    "lb-https://boxd.it/ham": "Rian Johnson",
    "lb-https://boxd.it/hCY2": "Don Hertzfeldt",
    "lb-https://boxd.it/hDPg": "Aneesh Chaganty",
    "lb-https://boxd.it/hE3i": "Sara Colangelo",
    "lb-https://boxd.it/hHUa": "Lee Chang-dong",
    "lb-https://boxd.it/hNVe": "Ari Aster",
    "lb-https://boxd.it/hq92": "Paul Feig",
    "lb-https://boxd.it/hTha": "Bong Joon Ho",
    "lb-https://boxd.it/hXlq": "Ruben Östlund",
    "lb-https://boxd.it/hyNk": "Ryusuke Hamaguchi",
    "lb-https://boxd.it/i1EQ": "Hu Bo",
    "lb-https://boxd.it/i3G": "Gavin O&#039;Connor",
    "lb-https://boxd.it/i4a": "Woody Allen",
    "lb-https://boxd.it/i4IQ": "Charlie Kaufman",
    "lb-https://boxd.it/i8C8": "Aaron Horvath, Michael Jelenic",
    "lb-https://boxd.it/ie6C": "Shinichiro Ushijima",
    "lb-https://boxd.it/iEEq": "Jimmy Chin, Elizabeth Chai Vasarhelyi",
    "lb-https://boxd.it/iehK": "Dexter Fletcher",
    "lb-https://boxd.it/iExu": "Renpei Tsukamoto",
    "lb-https://boxd.it/ifY6": "Hirokazu Kore-eda",
    "lb-https://boxd.it/IG": "Nicolas Winding Refn",
    "lb-https://boxd.it/IpPA": "Akihiro Toda",
    "lb-https://boxd.it/ixvm": "Alma Har&#039;el",
    "lb-https://boxd.it/J0": "Phil Lord, Christopher Miller",
    "lb-https://boxd.it/ja7e": "Clay Kaytis",
    "lb-https://boxd.it/jhxe": "Ari Aster",
    "lb-https://boxd.it/jiME": "Cory Finley",
    "lb-https://boxd.it/Jiy": "Carl Theodor Dreyer",
    "lb-https://boxd.it/jj4y": "Sam Mendes",
    "lb-https://boxd.it/jLP8": "Wes Anderson",
    "lb-https://boxd.it/jUk4": "Daniel Scheinert, Daniel Kwan",
    "lb-https://boxd.it/jWEA": "Rian Johnson",
    "lb-https://boxd.it/JY": "Baz Luhrmann",
    "lb-https://boxd.it/JZC": "Ingmar Bergman",
    "lb-https://boxd.it/k4BO": "Brady Corbet",
    "lb-https://boxd.it/kfE": "Asif Kapadia",
    "lb-https://boxd.it/Kgyu": "Tatsuya Yoshihara",
    "lb-https://boxd.it/kIky": "Lulu Wang",
    "lb-https://boxd.it/kjMW": "Mark Gustafson, Guillermo del Toro",
    "lb-https://boxd.it/Kjs": "Lena Dunham",
    "lb-https://boxd.it/kLDI": "Destin Daniel Cretton",
    "lb-https://boxd.it/kpk": "Lucrecia Martel",
    "lb-https://boxd.it/kPxE": "Makoto Shinkai",
    "lb-https://boxd.it/kSz4": "Kemp Powers, Justin K. Thompson et al",
    "lb-https://boxd.it/kv0q": "Vince Gilligan",
    "lb-https://boxd.it/l17I": "Noboru Iguchi",
    "lb-https://boxd.it/leq4": "Christopher Nolan",
    "lb-https://boxd.it/lGG": "Hong Sang-soo",
    "lb-https://boxd.it/LjA6": "Kiyotaka Oshiyama",
    "lb-https://boxd.it/lnRy": "Chloé Zhao",
    "lb-https://boxd.it/loRE": "Emerald Fennell",
    "lb-https://boxd.it/lQmY": "Ron Howard",
    "lb-https://boxd.it/lTpw": "Ryutaro Nakagawa",
    "lb-https://boxd.it/LZu": "Yasujirō Ozu",
    "lb-https://boxd.it/mL9M": "Lee Isaac Chung",
    "lb-https://boxd.it/mxuc": "Paul Thomas Anderson",
    "lb-https://boxd.it/nCFc": "Cooper Raiff",
    "lb-https://boxd.it/ncrS": "Patricia Marcoccia",
    "lb-https://boxd.it/nmS": "Peter Jackson",
    "lb-https://boxd.it/nrmo": "Shin Adachi",
    "lb-https://boxd.it/nTH0": "Paul Schrader",
    "lb-https://boxd.it/nwRw": "Jon Watts",
    "lb-https://boxd.it/oCkK": "Rian Johnson",
    "lb-https://boxd.it/oiNW": "Jesse Moss, Amanda McBaine",
    "lb-https://boxd.it/oIv0": "Emma Seligman",
    "lb-https://boxd.it/oL1s": "Takehiro Kubota, Hideki Ito et al",
    "lb-https://boxd.it/oL50": "Masaaki Yuasa, Akitoshi Yokoyama et al",
    "lb-https://boxd.it/oNB8": "Celine Song",
    "lb-https://boxd.it/oyws": "Joachim Trier",
    "lb-https://boxd.it/PP4": "David O. Russell",
    "lb-https://boxd.it/prk2": "James Reed, Philippa Ehrlich",
    "lb-https://boxd.it/psI": "Brad Bird",
    "lb-https://boxd.it/pUfA": "Denis Villeneuve",
    "lb-https://boxd.it/pZDC": "Nobuhiro Doi",
    "lb-https://boxd.it/Q6k": "Im Sang-soo",
    "lb-https://boxd.it/qjuK": "Tetsu Maeda",
    "lb-https://boxd.it/qp9e": "Park Chan-wook",
    "lb-https://boxd.it/qTKY": "Paul Thomas Anderson",
    "lb-https://boxd.it/R08": "Martin Scorsese",
    "lb-https://boxd.it/R6yo": "Sang-il Lee",
    "lb-https://boxd.it/rNS0": "Jason Woliner",
    "lb-https://boxd.it/RV6g": "Chris Smith",
    "lb-https://boxd.it/ryCQ": "Tatsushi Ōmori",
    "lb-https://boxd.it/sBnQ": "Rikiya Imaizumi",
    "lb-https://boxd.it/sRiW": "Gekidan Hitori",
    "lb-https://boxd.it/sv94": "Ryusuke Hamaguchi",
    "lb-https://boxd.it/svxU": "Jia Ling",
    "lb-https://boxd.it/Sw0": "Darren Aronofsky",
    "lb-https://boxd.it/T18": "Chantal Akerman",
    "lb-https://boxd.it/t8W": "Éric Rohmer",
    "lb-https://boxd.it/tABk": "George Miller",
    "lb-https://boxd.it/Tfa": "Anna Boden, Ryan Fleck",
    "lb-https://boxd.it/tTH2": "Rikiya Imaizumi",
    "lb-https://boxd.it/tw4c": "Darren Aronofsky",
    "lb-https://boxd.it/U1o": "Kon Ichikawa",
    "lb-https://boxd.it/u4Q": "Benjamin Heisenberg",
    "lb-https://boxd.it/ufwK": "Maggie Kang, Chris Appelhans",
    "lb-https://boxd.it/ujeK": "Hong Sung-eun",
    "lb-https://boxd.it/uRS": "Tetsuya Nakashima",
    "lb-https://boxd.it/uYE": "J.J. Abrams",
    "lb-https://boxd.it/vacW": "Keisuke Yoshida",
    "lb-https://boxd.it/vfZ0": "Yusuke Morii",
    "lb-https://boxd.it/ViK": "Kon Ichikawa",
    "lb-https://boxd.it/Vm8": "Paul Feig",
    "lb-https://boxd.it/vYla": "Nick Corirossi, Van Alpert",
    "lb-https://boxd.it/WKg": "Louis Malle",
    "lb-https://boxd.it/wUow": "Christopher Nolan",
    "lb-https://boxd.it/Xw0": "Mark Romanek",
    "lb-https://boxd.it/XXA": "Jūzō Itami",
    "lb-https://boxd.it/Y5u": "Jūzō Itami",
    "lb-https://boxd.it/yjVM": "Joseph Kosinski",
    "lb-https://boxd.it/yzY8": "Emma Kawawada",
    "lb-https://boxd.it/yZYe": "Sho Miyake",
    "lb-https://boxd.it/z14C": "Nick Park, Merlin Crossingham",
    "lb-https://boxd.it/ZQc": "Lee Chang-dong"
  },
  "bookPublicationYears": {
    "bm-10124617": "2013",
    "bm-11104585": "2016",
    "bm-12282073": "2014",
    "bm-12282211": "2014",
    "bm-12922494": "2015",
    "bm-12924793": "2016",
    "bm-12933970": "2018",
    "bm-13039237": "2018",
    "bm-13418516": "2019",
    "bm-13701067": "2019",
    "bm-13995539": "2019",
    "bm-14736496": "2019",
    "bm-16414148": "2020",
    "bm-16474791": "2020",
    "bm-19210962": "2022",
    "bm-19733446": "2022",
    "bm-19848539": "2022",
    "bm-20038182": "2022",
    "bm-20548664": "2023",
    "bm-21369241": "2023",
    "bm-21432065": "2023",
    "bm-21502189": "2023",
    "bm-21645409": "2023",
    "bm-22434268": "2025",
    "bm-22523091": "2025",
    "bm-366448": "1985",
    "bm-433350": "2008",
    "bm-457589": "2001",
    "bm-4749596": "2011",
    "bm-4786193": "2009",
    "bm-502251": "1968",
    "bm-547694": "2002",
    "bm-552620": "2004",
    "bm-555804": "1943",
    "bm-562729": "2005",
    "bm-569528": "1947",
    "bm-572234": "2000",
    "bm-573780": "2003",
    "bm-576878": "1948",
    "bm-576996": "2008",
    "bm-577586": "1991",
    "bm-578337": "1914",
    "bm-578733": "1949",
    "bm-579144": "1988",
    "bm-579985": "2003",
    "bm-580042": "1979",
    "bm-7846076": "2013",
    "bm-8100021": "2014",
    "bm-8123043": "2014",
    "bm-8150357": "2014",
    "bm-8317700": "2014",
    "bm-9296040": "2015",
    "bm-9337453": "2015",
    "bm-9810066": "2015",
    "gr-1": "2005",
    "gr-100464": "1997",
    "gr-10079308": "1983",
    "gr-100915": "1950",
    "gr-107533": "2006",
    "gr-11054461": "2011",
    "gr-11084145": "2011",
    "gr-11275": "1994",
    "gr-11297": "1987",
    "gr-113304": "2000",
    "gr-113436": "2002",
    "gr-114230": "1853",
    "gr-11468377": "2011",
    "gr-114954": "2005",
    "gr-114955": "2002",
    "gr-11539550": "2011",
    "gr-11870085": "2012",
    "gr-119073": "1980",
    "gr-119322": "1995",
    "gr-1202": "2005",
    "gr-12075": "1921",
    "gr-12079": "1990",
    "gr-12127750": "2012",
    "gr-121749": "1951",
    "gr-1232": "2001",
    "gr-12321": "1886",
    "gr-12322": "1881",
    "gr-1260022": "1864",
    "gr-12609433": "2012",
    "gr-1270379": "1943",
    "gr-12749": "1913",
    "gr-12898": "1949",
    "gr-13006": "1599",
    "gr-13079982": "1953",
    "gr-13081224": "1991",
    "gr-13139126": "2012",
    "gr-13145": "1993",
    "gr-13154952": "2012",
    "gr-133081281": "1920",
    "gr-13496": "1996",
    "gr-13573235": "2012",
    "gr-136251": "2007",
    "gr-13707734": "2011",
    "gr-13707738": "2011",
    "gr-1372419": "1971",
    "gr-1381": "2006",
    "gr-13895": "1993",
    "gr-13951996": "2009",
    "gr-140225": "1952",
    "gr-140963": "1913",
    "gr-1420": "1601",
    "gr-145660": "1953",
    "gr-148647": "1997",
    "gr-15241": "1954",
    "gr-154060": "1940",
    "gr-1554": "2004",
    "gr-15751404": "2013",
    "gr-15790875": "2012",
    "gr-15793150": "2013",
    "gr-15881": "1998",
    "gr-16158559": "2013",
    "gr-1618": "2003",
    "gr-162332": "1963",
    "gr-1653655": "2008",
    "gr-16640": "1774",
    "gr-17368274": "2013",
    "gr-17571564": "2013",
    "gr-17675118": "2014",
    "gr-17690": "1925",
    "gr-17716": "1951",
    "gr-17801": "1997",
    "gr-18050143": "2014",
    "gr-18122": "2000",
    "gr-18135": "1590",
    "gr-18213403": "2014",
    "gr-183015": "1992",
    "gr-18304": "1888",
    "gr-18512": "1955",
    "gr-18615474": "1899",
    "gr-18630": "1988",
    "gr-18883115": "1884",
    "gr-19351": "2000",
    "gr-19380": "1759",
    "gr-194746": "1948",
    "gr-19494": "1963",
    "gr-19506": "1818",
    "gr-19510": "1851",
    "gr-19522337": "2004",
    "gr-195774": "2002",
    "gr-2": "2003",
    "gr-20351058": "1866",
    "gr-2049993": "2007",
    "gr-20588698": "2014",
    "gr-20604826": "2014",
    "gr-207034": "2006",
    "gr-20758104": "2008",
    "gr-210255": "1884",
    "gr-2120932": "2008",
    "gr-2175": "1856",
    "gr-2195464": "2007",
    "gr-22318578": "2010",
    "gr-2248573": "2008",
    "gr-22628": "1999",
    "gr-227865": "2003",
    "gr-228665": "1990",
    "gr-231804": "1967",
    "gr-23256": "1997",
    "gr-2325825": "2007",
    "gr-233649": "1990",
    "gr-234225": "1965",
    "gr-24113": "1979",
    "gr-24128": "1596",
    "gr-243685": "1945",
    "gr-24601": "1857",
    "gr-247000": "1988",
    "gr-2493": "1895",
    "gr-2493973": "2008",
    "gr-249747": "2001",
    "gr-25191": "1964",
    "gr-25246": "1983",
    "gr-25335482": "1872",
    "gr-25489025": "2007",
    "gr-25899336": "2016",
    "gr-2612": "2000",
    "gr-2657": "1960",
    "gr-26634594": "2016",
    "gr-26721300": "1869",
    "gr-27161156": "2016",
    "gr-2732513": "2008",
    "gr-2753564": "2007",
    "gr-2767052": "2008",
    "gr-28186": "2006",
    "gr-28187": "2005",
    "gr-28193": "1994",
    "gr-28194": "2003",
    "gr-28195": "2005",
    "gr-2823": "1871",
    "gr-28385": "1919",
    "gr-2839": "1977",
    "gr-28921": "1989",
    "gr-2921082": "2008",
    "gr-2956": "1885",
    "gr-297673": "2007",
    "gr-3": "1997",
    "gr-30257963": "2018",
    "gr-30289": "2003",
    "gr-307791": "2003",
    "gr-31795": "1926",
    "gr-31947": "1979",
    "gr-32071": "1913",
    "gr-3228917": "2008",
    "gr-32321442": "2016",
    "gr-34": "1954",
    "gr-34448400": "2017",
    "gr-3467": "2004",
    "gr-34897": "1991",
    "gr-3552023": "2008",
    "gr-35666253": "2017",
    "gr-3636": "1993",
    "gr-36529": "1845",
    "gr-36796180": "2018",
    "gr-369704": "1994",
    "gr-369708": "1987",
    "gr-372100": "1884",
    "gr-375802": "1985",
    "gr-3774496": "1869",
    "gr-38357895": "2016",
    "gr-384786": "1978",
    "gr-386162": "1979",
    "gr-3876": "1926",
    "gr-39863479": "2019",
    "gr-40669542": "2009",
    "gr-4073199": "1968",
    "gr-41022133": "2013",
    "gr-41637836": "1997",
    "gr-42036377": "2018",
    "gr-4214": "2001",
    "gr-428": "1970",
    "gr-436806": "1928",
    "gr-439173": "1996",
    "gr-44652": "2006",
    "gr-452235": "1991",
    "gr-455388": "2000",
    "gr-4556058": "2009",
    "gr-45978": "2005",
    "gr-46165": "1920",
    "gr-4667024": "2009",
    "gr-4671": "1925",
    "gr-470321": "1934",
    "gr-4929": "2002",
    "gr-49455": "1864",
    "gr-49552": "1942",
    "gr-4981": "1969",
    "gr-5": "1999",
    "gr-5107": "1951",
    "gr-5113": "1957",
    "gr-5129": "1932",
    "gr-51323365": "2020",
    "gr-5148": "1959",
    "gr-52309": "1791",
    "gr-5246": "1911",
    "gr-53061": "1911",
    "gr-5308": "1947",
    "gr-5326": "1843",
    "gr-53358819": "2020",
    "gr-5348": "1999",
    "gr-5349": "1995",
    "gr-5358": "1995",
    "gr-5393037": "2001",
    "gr-5470": "1948",
    "gr-54846472": "1945",
    "gr-561456": "2007",
    "gr-577246": "1731",
    "gr-582067": "1963",
    "gr-58372": "1994",
    "gr-584564": "1878",
    "gr-584608": "1936",
    "gr-5907": "1937",
    "gr-59147138": "2022",
    "gr-6": "2000",
    "gr-60400": "2004",
    "gr-6088007": "1984",
    "gr-612188": "1962",
    "gr-6148028": "2009",
    "gr-6192": "1999",
    "gr-6199457": "1904",
    "gr-6200": "2002",
    "gr-62794": "1949",
    "gr-62798": "1956",
    "gr-62805": "1954",
    "gr-6290281": "1970",
    "gr-6330896": "2009",
    "gr-6388946": "2009",
    "gr-6394975": "1785",
    "gr-6493321": "2009",
    "gr-6514": "1963",
    "gr-65605": "1955",
    "gr-65641": "1953",
    "gr-667": "1938",
    "gr-676654": "2000",
    "gr-6792458": "2010",
    "gr-7090447": "2010",
    "gr-7126": "1844",
    "gr-7260188": "2010",
    "gr-752900": "1993",
    "gr-75812": "1987",
    "gr-760": "2004",
    "gr-7600589": "2009",
    "gr-7613": "1945",
    "gr-7624": "1954",
    "gr-7664041": "2011",
    "gr-767690": "1983",
    "gr-7728": "2005",
    "gr-7736182": "2010",
    "gr-7747374": "2010",
    "gr-77767": "1935",
    "gr-778581": "1975",
    "gr-7824997": "2010",
    "gr-78411": "1999",
    "gr-7865083": "1989",
    "gr-7967": "1986",
    "gr-80081": "2005",
    "gr-8032112": "2010",
    "gr-80324": "1783",
    "gr-80449": "1887",
    "gr-816017": "1990",
    "gr-817791": "2006",
    "gr-831893": "2006",
    "gr-8337": "1932",
    "gr-84119": "1954",
    "gr-84369": "1956",
    "gr-844573": "1951",
    "gr-851994": "1889",
    "gr-8520610": "2012",
    "gr-8852": "1623",
    "gr-890": "1937",
    "gr-8921": "1902",
    "gr-9160695": "2011",
    "gr-934622": "2007",
    "gr-9418327": "2011",
    "gr-94578": "1882",
    "gr-9520360": "2011",
    "gr-9532": "1999",
    "gr-9539": "1992",
    "gr-9555": "1993",
    "gr-9557": "1999",
    "gr-9692754": "2011",
    "gr-98955": "2005",
    "gr-9915": "1985",
    "gr-99561": "2005"
  }
};
