// Generated by scripts/build-goals-data.mjs
const goals = [
  {
    "id": "kanji-writing",
    "title": "漢字書き取り",
    "context": "Anki",
    "description": "Finish the 漢字書き取り deck on Anki every day.",
    "cadence": "daily",
    "startDate": "2026-08-22",
    "active": true,
    "done": []
  }
];
const goalsDayStartHour = 4;
