const mangaItems = [
  {
    "id": "mal-manga-3",
    "mal_id": 3,
    "title": "20th Century Boys",
    "english_title": "20th Century Boys",
    "author": "Urasawa, Naoki",
    "cover": "images/covers/mal-manga-3.jpg",
    "mal_url": "https://myanimelist.net/manga/3/20th_Century_Boys",
    "type": "Manga",
    "score": 9,
    "chapters_read": 249,
    "volumes_read": 22,
    "total_chapters": 249,
    "total_volumes": 22,
    "published": "Sep 27, 1999 to Apr 24, 2006",
    "published_year": 1999,
    "date_completed": "",
    "source_index": 0
  },
  {
    "id": "mal-manga-24705",
    "mal_id": 24705,
    "title": "Aku no Hana",
    "english_title": "The Flowers of Evil",
    "author": "Oshimi, Shuuzou",
    "cover": "images/covers/mal-manga-24705.jpg",
    "mal_url": "https://myanimelist.net/manga/24705/Aku_no_Hana",
    "type": "Manga",
    "score": 10,
    "chapters_read": 58,
    "volumes_read": 11,
    "total_chapters": 58,
    "total_volumes": 11,
    "published": "Sep 9, 2009 to May 9, 2014",
    "published_year": 2009,
    "date_completed": "",
    "source_index": 1
  },
  {
    "id": "mal-manga-46282",
    "mal_id": 46282,
    "title": "Chikan Otoko",
    "english_title": "",
    "author": "Yokota, Takuma",
    "cover": "images/covers/mal-manga-46282.jpg",
    "mal_url": "https://myanimelist.net/manga/46282/Chikan_Otoko",
    "type": "Manga",
    "score": 9,
    "chapters_read": 21,
    "volumes_read": null,
    "total_chapters": 21,
    "total_volumes": null,
    "published": "2004",
    "published_year": 2004,
    "date_completed": "",
    "source_index": 2
  },
  {
    "id": "mal-manga-21",
    "mal_id": 21,
    "title": "Death Note",
    "english_title": "Death Note",
    "author": "Obata, Takeshi, Ohba, Tsugumi",
    "cover": "images/covers/mal-manga-21.jpg",
    "mal_url": "https://myanimelist.net/manga/21/Death_Note",
    "type": "Manga",
    "score": 9,
    "chapters_read": 108,
    "volumes_read": 12,
    "total_chapters": 108,
    "total_volumes": 12,
    "published": "Dec 1, 2003 to May 15, 2006",
    "published_year": 2003,
    "date_completed": "",
    "source_index": 3
  },
  {
    "id": "mal-manga-42",
    "mal_id": 42,
    "title": "Dragon Ball",
    "english_title": "Dragon Ball",
    "author": "Toriyama, Akira",
    "cover": "images/covers/mal-manga-42.jpg",
    "mal_url": "https://myanimelist.net/manga/42/Dragon_Ball",
    "type": "Manga",
    "score": 8,
    "chapters_read": 520,
    "volumes_read": 42,
    "total_chapters": 520,
    "total_volumes": 42,
    "published": "Nov 20, 1984 to May 23, 1995",
    "published_year": 1984,
    "date_completed": "",
    "source_index": 4
  },
  {
    "id": "mal-manga-10978",
    "mal_id": 10978,
    "title": "Major",
    "english_title": "",
    "author": "Mitsuda, Takuya",
    "cover": "images/covers/mal-manga-10978.jpg",
    "mal_url": "https://myanimelist.net/manga/10978/Major",
    "type": "Manga",
    "score": 8,
    "chapters_read": 747,
    "volumes_read": 78,
    "total_chapters": 747,
    "total_volumes": 78,
    "published": "Jul 13, 1994 to Jul 7, 2010",
    "published_year": 1994,
    "date_completed": "",
    "source_index": 5
  },
  {
    "id": "mal-manga-1",
    "mal_id": 1,
    "title": "Monster",
    "english_title": "Monster",
    "author": "Urasawa, Naoki",
    "cover": "images/covers/mal-manga-1.jpg",
    "mal_url": "https://myanimelist.net/manga/1/Monster",
    "type": "Manga",
    "score": 10,
    "chapters_read": 162,
    "volumes_read": 18,
    "total_chapters": 162,
    "total_volumes": 18,
    "published": "Dec 5, 1994 to Dec 20, 2001",
    "published_year": 1994,
    "date_completed": "",
    "source_index": 6
  },
  {
    "id": "mal-manga-8967",
    "mal_id": 8967,
    "title": "Onanie Master Kurosawa",
    "english_title": "",
    "author": "Yokota, Takuma, Ise, Katsura",
    "cover": "images/covers/mal-manga-8967.jpg",
    "mal_url": "https://myanimelist.net/manga/8967/Onanie_Master_Kurosawa",
    "type": "Manga",
    "score": 9,
    "chapters_read": 31,
    "volumes_read": 4,
    "total_chapters": 31,
    "total_volumes": 4,
    "published": "Sep 2007 to Mar 2008",
    "published_year": 2007,
    "date_completed": "",
    "source_index": 7
  },
  {
    "id": "mal-manga-11734",
    "mal_id": 11734,
    "title": "Watashitachi no Shiawase na Jikan",
    "english_title": "",
    "author": "Yumeka, Sumomo",
    "cover": "images/covers/mal-manga-11734.jpg",
    "mal_url": "https://myanimelist.net/manga/11734/Watashitachi_no_Shiawase_na_Jikan",
    "type": "Manga",
    "score": 9,
    "chapters_read": 8,
    "volumes_read": 1,
    "total_chapters": 8,
    "total_volumes": 1,
    "published": "Mar 28, 2008 to Aug 22, 2008",
    "published_year": 2008,
    "date_completed": "",
    "source_index": 8
  }
];
