// Generated by scripts/build-reading-list-data.mjs
const readingListEntries = [
  {
    "title": "Fortune's Formula: The Untold Story of the Scientific Betting System That Beat the Casinos and Wall Street",
    "author": "William Poundstone",
    "goodreadsId": "186124",
    "dateAdded": "2026-02-13"
  },
  {
    "title": "The Everywhere Millionaire: Who Is Really Rich in America and How They Got There",
    "author": "Owen Zidar",
    "goodreadsId": "244967568",
    "dateAdded": "2026-02-12"
  },
  {
    "title": "MITI and the Japanese Miracle: The Growth of Industrial Policy, 1925-1975",
    "author": "Chalmers Johnson",
    "goodreadsId": "771283",
    "dateAdded": "2026-02-06"
  },
  {
    "title": "The New Paradigm for Financial Markets: The Credit Crisis of 2008 and What It Means",
    "author": "George Soros",
    "goodreadsId": "3191235",
    "dateAdded": "2026-02-06"
  },
  {
    "title": "The Soros Lectures: At the Central European University",
    "author": "George Soros",
    "goodreadsId": "7651910",
    "dateAdded": "2026-02-06"
  },
  {
    "title": "Reminiscences of a Stock Operator",
    "author": "Edwin Lefèvre",
    "goodreadsId": "100779",
    "dateAdded": "2026-01-25"
  },
  {
    "title": "The Black Swan: The Impact of the Highly Improbable",
    "author": "Nassim Nicholas Taleb",
    "goodreadsId": "242472",
    "dateAdded": "2026-01-25"
  },
  {
    "title": "The Education of a Speculator",
    "author": "Victor Niederhoffer",
    "goodreadsId": "495065",
    "dateAdded": "2026-01-25"
  },
  {
    "title": "Napoléon",
    "author": "Stendhal",
    "goodreadsId": "1176160",
    "dateAdded": "2026-01-23"
  },
  {
    "title": "China: A New History",
    "author": "John King Fairbank",
    "goodreadsId": "178794",
    "dateAdded": "2026-01-16"
  },
  {
    "title": "Taipei People",
    "author": "Pai Hsien-yung",
    "goodreadsId": "1035825",
    "dateAdded": "2026-01-15"
  },
  {
    "title": "China: A Macro History (An East Gate Book)",
    "author": "Ray Huang",
    "goodreadsId": "734666",
    "dateAdded": "2026-01-13"
  },
  {
    "title": "My Life Between Japan and America",
    "author": "Edwin O. Reischauer",
    "goodreadsId": "971850",
    "dateAdded": "2026-01-13"
  },
  {
    "title": "Central Banking 101",
    "author": "Joseph J. Wang",
    "goodreadsId": "56863052",
    "dateAdded": "2026-01-07"
  },
  {
    "title": "The Economics of Money, Banking, and Financial Markets (Addison-Wesley Series in Economics)",
    "author": "Frederic S. Mishkin",
    "goodreadsId": "299577",
    "dateAdded": "2026-01-07"
  },
  {
    "title": "On the Marble Cliffs",
    "author": "Ernst Jünger",
    "goodreadsId": "501415",
    "dateAdded": "2026-01-05"
  },
  {
    "title": "Market Wizards: Interviews with Top Traders (Market Wizards, #1)",
    "author": "Jack D. Schwager",
    "goodreadsId": "966769",
    "dateAdded": "2026-01-03"
  },
  {
    "title": "Journal I, 1945-1955",
    "author": "Mircea Eliade",
    "goodreadsId": "440056",
    "dateAdded": "2025-10-27"
  },
  {
    "title": "Wild Swans: Three Daughters of China",
    "author": "Jung Chang",
    "goodreadsId": "1848",
    "dateAdded": "2025-10-27"
  },
  {
    "title": "A History of Interest Rates (Wiley Finance)",
    "author": "Sidney Homer",
    "goodreadsId": "920156",
    "dateAdded": "2025-10-26"
  },
  {
    "title": "The Demon in Democracy: Totalitarian Temptations in Free Societies",
    "author": "Ryszard Legutko",
    "goodreadsId": "25898468",
    "dateAdded": "2025-10-26"
  },
  {
    "title": "The Explanation of Ideology: Family Structure and Social Systems (Family, Sexuality and Social Relations in Past Times)",
    "author": "Emmanuel Todd",
    "goodreadsId": "1058107",
    "dateAdded": "2025-10-07"
  },
  {
    "title": "Men and Marriage",
    "author": "George Gilder",
    "goodreadsId": "195644131",
    "dateAdded": "2025-10-05"
  },
  {
    "title": "A Time of Gifts (Trilogy, #1)",
    "author": "Patrick Leigh Fermor",
    "goodreadsId": "253984",
    "dateAdded": "2025-10-04"
  },
  {
    "title": "Jude the Obscure",
    "author": "Thomas Hardy",
    "goodreadsId": "50798",
    "dateAdded": "2025-10-04"
  },
  {
    "title": "Story of My Life: The Autobiography of George Sand (Women Writers in Translation)",
    "author": "George Sand",
    "goodreadsId": "104263",
    "dateAdded": "2025-10-04"
  },
  {
    "title": "An Introduction to Psychometrics and Psychological Assessment: Using, Interpreting and Developing Tests",
    "author": "Colin Cooper",
    "goodreadsId": "214876579",
    "dateAdded": "2025-09-27"
  },
  {
    "title": "Tales From Shakespeare",
    "author": "Charles Lamb",
    "goodreadsId": "42036",
    "dateAdded": "2025-09-15"
  },
  {
    "title": "Empire of Signs",
    "author": "Roland Barthes",
    "goodreadsId": "770926",
    "dateAdded": "2025-09-14"
  },
  {
    "title": "The Leopard",
    "author": "Giuseppe Tomasi di Lampedusa",
    "goodreadsId": "625094",
    "dateAdded": "2025-08-30"
  },
  {
    "title": "Addresses to the German Nation",
    "author": "Johann Gottlieb Fichte",
    "goodreadsId": "7690321",
    "dateAdded": "2025-07-28"
  },
  {
    "title": "The Vocation of Man",
    "author": "Johann Gottlieb Fichte",
    "goodreadsId": "866000",
    "dateAdded": "2025-07-28"
  },
  {
    "title": "The South Vindicated from the Treason and Fanaticism of the Northern Abolitionists",
    "author": "William Drayton",
    "goodreadsId": "26302936",
    "dateAdded": "2025-07-22"
  },
  {
    "title": "Kuhaku & Other Accounts from Japan",
    "author": "Bruce Rutledge",
    "goodreadsId": "642253",
    "dateAdded": "2025-06-22"
  },
  {
    "title": "Pilgrim at Tinker Creek",
    "author": "Annie Dillard",
    "goodreadsId": "12527",
    "dateAdded": "2025-06-22"
  },
  {
    "title": "Train Dreams",
    "author": "Denis Johnson",
    "goodreadsId": "12991188",
    "dateAdded": "2025-06-22"
  },
  {
    "title": "Demystifying Pearl Harbor: A New Perspective from Japan",
    "author": "Iguchi Takeo",
    "goodreadsId": "10353069",
    "dateAdded": "2025-06-19"
  },
  {
    "title": "The Pearl Harbor Myth: Rethinking the Unthinkable",
    "author": "George Victor",
    "goodreadsId": "124833",
    "dateAdded": "2025-06-19"
  },
  {
    "title": "What's Wrong with the World",
    "author": "G.K. Chesterton",
    "goodreadsId": "184565",
    "dateAdded": "2025-06-19"
  },
  {
    "title": "Zen-Man Ikkyu",
    "author": "James H. Sanford",
    "goodreadsId": "319047",
    "dateAdded": "2025-06-19"
  },
  {
    "title": "The Devil's Chessboard: Allen Dulles, the CIA, and the Rise of America's Secret Government",
    "author": "David Talbot",
    "goodreadsId": "24723229",
    "dateAdded": "2025-06-15"
  },
  {
    "title": "The Tragedy of Europe: a Day-By-Day Commentary on the Second World War, Complete in 5 Vols.",
    "author": "Francis Neilson",
    "goodreadsId": "163949236",
    "dateAdded": "2025-06-04"
  },
  {
    "title": "The Golden Notebook",
    "author": "Doris Lessing",
    "goodreadsId": "24100",
    "dateAdded": "2025-05-29"
  },
  {
    "title": "Elementary Striking - Strategies for Boxing, Kickboxing and MMA",
    "author": "Jack Slack",
    "goodreadsId": "25400291",
    "dateAdded": "2025-05-18"
  },
  {
    "title": "Finding the Art: Essays on the Principles, Tactics and Techniques Which Govern Combat Sports",
    "author": "Jack Slack",
    "goodreadsId": "25974735",
    "dateAdded": "2025-05-18"
  },
  {
    "title": "Child Composers in the Old Conservatories: How Orphans Became Elite Musicians",
    "author": "Robert O Gjerdingen",
    "goodreadsId": "49046502",
    "dateAdded": "2025-03-09"
  },
  {
    "title": "Music in the Galant Style",
    "author": "Robert O Gjerdingen",
    "goodreadsId": "23028082",
    "dateAdded": "2025-03-09"
  },
  {
    "title": "Revolutionary Road",
    "author": "Richard Yates",
    "goodreadsId": "48328",
    "dateAdded": "2025-02-27"
  },
  {
    "title": "The Man Who Would Be Queen: The Science of Gender-Bending and Transsexualism",
    "author": "J. Michael Bailey",
    "goodreadsId": "747417",
    "dateAdded": "2025-02-19"
  },
  {
    "title": "Reaping and Sowing (Récoltes et semailles) The Life of a Mathematician: Reflections and Bearing Witness",
    "author": "Alexandre Grothendieck",
    "goodreadsId": "48573989",
    "dateAdded": "2025-02-14"
  },
  {
    "title": "The Glass Castle",
    "author": "Jeannette Walls",
    "goodreadsId": "7445",
    "dateAdded": "2025-02-02"
  },
  {
    "title": "Against the Odds: An Autobiography",
    "author": "James Dyson",
    "goodreadsId": "955045",
    "dateAdded": "2025-01-28"
  },
  {
    "title": "Gray Mirror: Fascicle I: Disturbance",
    "author": "Curtis Yarvin",
    "goodreadsId": "223991638",
    "dateAdded": "2025-01-28"
  },
  {
    "title": "How To Get Rich",
    "author": "Felix Dennis",
    "goodreadsId": "1837402",
    "dateAdded": "2025-01-28"
  },
  {
    "title": "Unqualified Reservations, Vol. 01",
    "author": "Curtis Yarvin",
    "goodreadsId": "193539945",
    "dateAdded": "2025-01-28"
  },
  {
    "title": "A Sorrow Beyond Dreams",
    "author": "Peter Handke",
    "goodreadsId": "24482",
    "dateAdded": "2025-01-24"
  },
  {
    "title": "Boyhood (Scenes from Provincial Life #1)",
    "author": "J.M. Coetzee",
    "goodreadsId": "6198",
    "dateAdded": "2025-01-24"
  },
  {
    "title": "Summertime (Scenes from Provincial Life #3)",
    "author": "J.M. Coetzee",
    "goodreadsId": "6337163",
    "dateAdded": "2025-01-24"
  },
  {
    "title": "The Goalie's Anxiety at the Penalty Kick",
    "author": "Peter Handke",
    "goodreadsId": "1444718",
    "dateAdded": "2025-01-24"
  },
  {
    "title": "The Left-Handed Woman",
    "author": "Peter Handke",
    "goodreadsId": "1131696",
    "dateAdded": "2025-01-24"
  },
  {
    "title": "History Of Friedrich II Of Prussia Called Frederick The Great V1",
    "author": "Thomas Carlyle",
    "goodreadsId": "11897887",
    "dateAdded": "2025-01-23"
  },
  {
    "title": "Tower",
    "author": "Bae Myung-hoon",
    "goodreadsId": "54609416",
    "dateAdded": "2025-01-13"
  },
  {
    "title": "The Anarchy: The East India Company, Corporate Violence, and the Pillage of an Empire",
    "author": "William Dalrymple",
    "goodreadsId": "42972023",
    "dateAdded": "2025-01-07"
  },
  {
    "title": "The Collapse of Antiquity",
    "author": "Michael Hudson",
    "goodreadsId": "123381858",
    "dateAdded": "2025-01-06"
  },
  {
    "title": "Two Arms and a Head: The Death of a Newly Paraplegic Philosopher",
    "author": "Clayton Atreus",
    "goodreadsId": "41183735",
    "dateAdded": "2024-12-26"
  },
  {
    "title": "The Intellectual Life: Its Spirit, Conditions, Methods",
    "author": "Antonin Sertillanges",
    "goodreadsId": "549384",
    "dateAdded": "2024-12-22"
  },
  {
    "title": "The WEIRDest People in the World: How the West Became Psychologically Peculiar and Particularly Prosperous",
    "author": "Joseph Henrich",
    "goodreadsId": "51710349",
    "dateAdded": "2024-12-19"
  },
  {
    "title": "A Fire Upon the Deep (Zones of Thought, #1)",
    "author": "Vernor Vinge",
    "goodreadsId": "77711",
    "dateAdded": "2024-12-18"
  },
  {
    "title": "Rainbows End",
    "author": "Vernor Vinge",
    "goodreadsId": "102439",
    "dateAdded": "2024-12-18"
  },
  {
    "title": "Tatja Grimm's World",
    "author": "Vernor Vinge",
    "goodreadsId": "167841",
    "dateAdded": "2024-12-18"
  },
  {
    "title": "A Child of the Century",
    "author": "Ben Hecht",
    "goodreadsId": "612650",
    "dateAdded": "2024-12-14"
  },
  {
    "title": "A guide for the bedevilled",
    "author": "Ben Hecht",
    "goodreadsId": "132385214",
    "dateAdded": "2024-12-14"
  },
  {
    "title": "On War",
    "author": "Carl von Clausewitz",
    "goodreadsId": "117031",
    "dateAdded": "2024-12-14"
  },
  {
    "title": "District",
    "author": "Tony Duvert",
    "goodreadsId": "34416648",
    "dateAdded": "2024-09-29"
  },
  {
    "title": "Olinger Stories",
    "author": "John Updike",
    "goodreadsId": "6374256",
    "dateAdded": "2024-09-22"
  },
  {
    "title": "By Night in Chile",
    "author": "Roberto Bolaño",
    "goodreadsId": "63031",
    "dateAdded": "2024-06-26"
  },
  {
    "title": "Family Ties",
    "author": "Clarice Lispector",
    "goodreadsId": "761351",
    "dateAdded": "2024-06-26"
  },
  {
    "title": "The Prize: The Epic Quest for Oil, Money, and Power",
    "author": "Daniel Yergin",
    "goodreadsId": "169354",
    "dateAdded": "2024-06-26"
  },
  {
    "title": "The Churchill Legend",
    "author": "Francis Neilson",
    "goodreadsId": "13481352",
    "dateAdded": "2024-06-11"
  },
  {
    "title": "The tragedy of Europe; a day by day commentary on the Second World War. Volume v.4 1946 [Leather Bound]",
    "author": "Francis Neilson",
    "goodreadsId": "146764531",
    "dateAdded": "2024-06-11"
  },
  {
    "title": "Fall of the Double Eagle: The Battle for Galicia and the Demise of Austria-Hungary",
    "author": "John R. Schindler",
    "goodreadsId": "24453976",
    "dateAdded": "2024-06-10"
  },
  {
    "title": "The Curtain Rises",
    "author": "Quentin Reynolds",
    "goodreadsId": "2680741",
    "dateAdded": "2024-06-10"
  },
  {
    "title": "Unholy Terror: Bosnia, Al-Qa'ida, and the Rise of Global Jihad",
    "author": "John R. Schindler",
    "goodreadsId": "425772",
    "dateAdded": "2024-06-10"
  },
  {
    "title": "How Diplomats Make War",
    "author": "Francis Neilson",
    "goodreadsId": "1871167",
    "dateAdded": "2024-06-09"
  },
  {
    "title": "The Politics of Hunger: The Allied Blockade of Germany, 1915-1919",
    "author": "C. Paul Vincent",
    "goodreadsId": "6357332",
    "dateAdded": "2024-06-09"
  },
  {
    "title": "As We Go Marching: A Biting Indictment of the Coming of Domestic Fascism in America",
    "author": "John T. Flynn",
    "goodreadsId": "2858907",
    "dateAdded": "2024-06-08"
  },
  {
    "title": "Public Opinion",
    "author": "Walter Lippmann",
    "goodreadsId": "920442",
    "dateAdded": "2024-06-08"
  },
  {
    "title": "Barbarians at the Gate: The Fall of RJR Nabisco",
    "author": "Bryan Burrough",
    "goodreadsId": "781182",
    "dateAdded": "2024-06-07"
  },
  {
    "title": "Days of Rage: America's Radical Underground, the FBI, and the Forgotten Age of Revolutionary Violence",
    "author": "Bryan Burrough",
    "goodreadsId": "22571602",
    "dateAdded": "2024-06-07"
  },
  {
    "title": "How to Make a Few Billion Dollars",
    "author": "Brad Jacobs",
    "goodreadsId": "199249408",
    "dateAdded": "2024-06-07"
  },
  {
    "title": "Men, Women & Manners in Colonial Times",
    "author": "Sydney George Fisher",
    "goodreadsId": "20702781",
    "dateAdded": "2024-05-26"
  },
  {
    "title": "The Evolution of the Constitution of the",
    "author": "Sydney George Fisher",
    "goodreadsId": "5113792",
    "dateAdded": "2024-05-26"
  },
  {
    "title": "The Making of Pennsylvania",
    "author": "Sydney George Fisher",
    "goodreadsId": "7102619",
    "dateAdded": "2024-05-26"
  },
  {
    "title": "The Quaker Colonies: History of the Early Quaker Settlements in New England and the Delaware River",
    "author": "Sydney George Fisher",
    "goodreadsId": "57304201",
    "dateAdded": "2024-05-26"
  },
  {
    "title": "Breaking Through: My Life in Science",
    "author": "Katalin Karikó",
    "goodreadsId": "123025953",
    "dateAdded": "2024-05-25"
  },
  {
    "title": "The History of the Colony of Massachusetts-Bay",
    "author": "Thomas   Hutchinson",
    "goodreadsId": "3746514",
    "dateAdded": "2024-05-25"
  },
  {
    "title": "History of the War of the Independence of the United States of America, Vol. 1 (Classic Reprint)",
    "author": "Carlo Botta",
    "goodreadsId": "32081669",
    "dateAdded": "2024-05-24"
  },
  {
    "title": "How we squandered the Reich",
    "author": "Reinhard Spitzy",
    "goodreadsId": "2839118",
    "dateAdded": "2024-05-24"
  },
  {
    "title": "Is Administrative Law Unlawful?",
    "author": "Philip Hamburger",
    "goodreadsId": "18526698",
    "dateAdded": "2024-05-24"
  },
  {
    "title": "The Suicide of Europe: Memoirs of Prince Michel Sturdza",
    "author": "Michael Sturdza",
    "goodreadsId": "13540713",
    "dateAdded": "2024-05-24"
  },
  {
    "title": "The Diary of a Country Priest",
    "author": "Georges Bernanos",
    "goodreadsId": "63672",
    "dateAdded": "2024-05-23"
  },
  {
    "title": "Why China Leads the World: Talent at the Top, Data in the Middle, Democracy at the Bottom",
    "author": "Godfree Roberts",
    "goodreadsId": "56326535",
    "dateAdded": "2024-05-23"
  },
  {
    "title": "Fog (Translated): Mist from Miguel Unamuno",
    "author": "Miguel de Unamuno",
    "goodreadsId": "70867107",
    "dateAdded": "2024-05-14"
  },
  {
    "title": "Health Economics & Policy [with Economic Applications]",
    "author": "James W. Henderson",
    "goodreadsId": "497491",
    "dateAdded": "2024-05-14"
  },
  {
    "title": "The Economics of Health And Health Care",
    "author": "Sherman Folland",
    "goodreadsId": "56164",
    "dateAdded": "2024-05-14"
  },
  {
    "title": "The Social Transformation of American Medicine: The Rise of a Sovereign Profession and the Making of a Vast Industry",
    "author": "Paul Starr",
    "goodreadsId": "142863",
    "dateAdded": "2024-05-14"
  },
  {
    "title": "Tragic Sense of Life",
    "author": "Miguel de Unamuno",
    "goodreadsId": "144915",
    "dateAdded": "2024-05-14"
  },
  {
    "title": "Memoirs (Tauber Institute for the Study of European Jewry)",
    "author": "Hans Jonas",
    "goodreadsId": "3392962",
    "dateAdded": "2024-05-12"
  },
  {
    "title": "The Gnostic Religion: The Message of the Alien God and the Beginnings of Christianity",
    "author": "Hans Jonas",
    "goodreadsId": "650432",
    "dateAdded": "2024-05-12"
  },
  {
    "title": "The Legitimacy of the Modern Age (Studies in Contemporary German Social Thought)",
    "author": "Hans Blumenberg",
    "goodreadsId": "251465",
    "dateAdded": "2024-05-12"
  },
  {
    "title": "Work on Myth (Studies in Contemporary German Social Thought)",
    "author": "Hans Blumenberg",
    "goodreadsId": "778686",
    "dateAdded": "2024-05-12"
  },
  {
    "title": "Straight to Hell: True Tales of Deviance, Debauchery, and Billion-Dollar Deals",
    "author": "John LeFevre",
    "goodreadsId": "21535674",
    "dateAdded": "2024-05-06"
  },
  {
    "title": "The Art of Doing Science and Engineering: Learning to Learn",
    "author": "Richard Hamming",
    "goodreadsId": "530415",
    "dateAdded": "2024-05-06"
  },
  {
    "title": "The Hall of Uselessness: Collected Essays",
    "author": "Simon Leys",
    "goodreadsId": "11951046",
    "dateAdded": "2024-05-06"
  },
  {
    "title": "Neurosis and Human Growth: The Struggle Towards Self-Realization",
    "author": "Karen Horney",
    "goodreadsId": "130383",
    "dateAdded": "2024-05-03"
  },
  {
    "title": "My First Seventy-Six Years",
    "author": "Hjalmar Schacht",
    "goodreadsId": "33280307",
    "dateAdded": "2024-04-28"
  },
  {
    "title": "The Japanese Empire: Grand Strategy from the Meiji Restoration to the Pacific War",
    "author": "S.C.M. Paine",
    "goodreadsId": "30423569",
    "dateAdded": "2024-04-22"
  },
  {
    "title": "The Wars for Asia, 1911-1949",
    "author": "S.C.M. Paine",
    "goodreadsId": "15868343",
    "dateAdded": "2024-04-22"
  },
  {
    "title": "Of Time and Tide",
    "author": "Atsiri Thammachoat",
    "goodreadsId": "6090122",
    "dateAdded": "2024-04-12"
  },
  {
    "title": "The Prostitute (Oxford in Asia Paperbacks)",
    "author": "ก.สุรางคนางค์",
    "goodreadsId": "1590636",
    "dateAdded": "2024-04-12"
  },
  {
    "title": "Letters Of Clara Schumann And Johannes Brahms, 1853 1896",
    "author": "Clara Schumann",
    "goodreadsId": "2803716",
    "dateAdded": "2024-03-25"
  },
  {
    "title": "One Man in His Time",
    "author": "Serge Obolensky",
    "goodreadsId": "2273463",
    "dateAdded": "2024-03-25"
  },
  {
    "title": "The Decameron",
    "author": "Giovanni Boccaccio",
    "goodreadsId": "51799",
    "dateAdded": "2024-03-19"
  },
  {
    "title": "Genius: The Natural History of Creativity (Problems in the Behavioural Sciences, Series Number 12)",
    "author": "Hans Jürgen Eysenck",
    "goodreadsId": "943715",
    "dateAdded": "2024-02-01"
  },
  {
    "title": "The Son Also Rises: Surnames and the History of Social Mobility",
    "author": "Gregory Clark",
    "goodreadsId": "18730716",
    "dateAdded": "2024-01-06"
  },
  {
    "title": "Shimazaki: Before the Dawn Paper (Miscellany; 135) by Toson Shimazaki (1988-07-31)",
    "author": "Tōson Shimazaki",
    "goodreadsId": "144282817",
    "dateAdded": "2024-01-04"
  },
  {
    "title": "Deng Xiaoping and the Transformation of China",
    "author": "Ezra F. Vogel",
    "goodreadsId": "11472345",
    "dateAdded": "2024-01-02"
  },
  {
    "title": "Japan's Emergence as a Modern State: Political and Economic Problems of the Meiji Period, 60th Anniversary Edition",
    "author": "E. Herbert Norman",
    "goodreadsId": "3242286",
    "dateAdded": "2023-12-24"
  },
  {
    "title": "China's Examination Hell: The Civil Service Examinations of Imperial China",
    "author": "Ichisada Miyazaki",
    "goodreadsId": "766116",
    "dateAdded": "2023-12-23"
  },
  {
    "title": "Leonardo the Florentine: A Study in Personality",
    "author": "Rachel Annand Taylor",
    "goodreadsId": "14291966",
    "dateAdded": "2023-12-23"
  },
  {
    "title": "The Rise and Fall of the EAST: How Exams, Autocracy, Stability, and Technology Brought China Success, and Why They Might Lead to Its Decline",
    "author": "Yasheng Huang",
    "goodreadsId": "195917358",
    "dateAdded": "2023-12-03"
  },
  {
    "title": "Death Without Weeping: The Violence of Everyday Life in Brazil",
    "author": "Nancy Scheper-Hughes",
    "goodreadsId": "242383",
    "dateAdded": "2023-11-19"
  },
  {
    "title": "A Burglar's Guide to the City",
    "author": "Geoff Manaugh",
    "goodreadsId": "22237142",
    "dateAdded": "2023-10-20"
  },
  {
    "title": "The Nomos of the Earth: In the International Law of the Jus Publicum Europaeum",
    "author": "Carl Schmitt",
    "goodreadsId": "322348",
    "dateAdded": "2023-10-18"
  },
  {
    "title": "High Growth Handbook: Scaling Startups from 10 to 10,000 People",
    "author": "Elad Gil",
    "goodreadsId": "40536148",
    "dateAdded": "2023-10-16"
  },
  {
    "title": "No Rules Rules: Netflix and the Culture of Reinvention",
    "author": "Reed Hastings",
    "goodreadsId": "49099937",
    "dateAdded": "2023-10-16"
  },
  {
    "title": "Critique and Crises: Enlightenment and the Pathogenesis of Modern Society (Studies in Contemporary German Social Thought)",
    "author": "Reinhart Koselleck",
    "goodreadsId": "329805",
    "dateAdded": "2023-10-11"
  },
  {
    "title": "From Third World to First: A Statesman’s Powerful Story of Transformation from Poverty to National Leadership",
    "author": "Lee Kuan Yew",
    "goodreadsId": "144409",
    "dateAdded": "2023-09-08"
  },
  {
    "title": "The Singapore Story: Memoirs of Lee Kuan Yew",
    "author": "Lee Kuan Yew",
    "goodreadsId": "326981",
    "dateAdded": "2023-09-08"
  },
  {
    "title": "Back Door to War, The Roosevelt Foreign Policy, 1933 - 1941",
    "author": "Charles Callan Tansill",
    "goodreadsId": "2340869",
    "dateAdded": "2023-08-10"
  },
  {
    "title": "Flicker",
    "author": "Theodore Roszak",
    "goodreadsId": "243162",
    "dateAdded": "2023-08-07"
  },
  {
    "title": "Lost Time: Lectures on Proust in a Soviet Prison Camp",
    "author": "Józef Czapski",
    "goodreadsId": "40378238",
    "dateAdded": "2023-07-17"
  },
  {
    "title": "The Life of Henry Brulard",
    "author": "Stendhal",
    "goodreadsId": "75600",
    "dateAdded": "2023-07-15"
  },
  {
    "title": "The Red and the Black",
    "author": "Stendhal",
    "goodreadsId": "14662",
    "dateAdded": "2023-07-15"
  },
  {
    "title": "Bees (CW 351)",
    "author": "Rudolf Steiner",
    "goodreadsId": "597965",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "Calendar of the Soul: The Year Participated (CW 40) (Meditations)",
    "author": "Rudolf Steiner",
    "goodreadsId": "2405073",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "Colour",
    "author": "Rudolf Steiner",
    "goodreadsId": "2749894",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "How to Know Higher Worlds: A Modern Path of Initiation (Classics in Anthroposophy)",
    "author": "Rudolf Steiner",
    "goodreadsId": "850873",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "Intuitive Thinking As a Spiritual Path: A Philosophy of Freedom (Classics in Anthroposophy)",
    "author": "Rudolf Steiner",
    "goodreadsId": "569375",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "Road To Self Knowledge",
    "author": "Rudolf Steiner",
    "goodreadsId": "19267036",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "The Art of the Novel",
    "author": "Milan Kundera",
    "goodreadsId": "28637",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "The Education of the Child: And Early Lectures on Education (Foundations of Waldorf Education, 25)",
    "author": "Rudolf Steiner",
    "goodreadsId": "916447",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "The Fourth Dimension: Sacred Geometry, Alchemy & Mathematics (CW 324a)",
    "author": "Rudolf Steiner",
    "goodreadsId": "471326",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "The Kingdom of Childhood : Introductory Talks on Waldorf Education",
    "author": "Rudolf Steiner",
    "goodreadsId": "2342262",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "美国反对美国",
    "author": "Wang Huning",
    "goodreadsId": "58844127",
    "dateAdded": "2023-07-14"
  },
  {
    "title": "A Ragged Schooling: Growing Up in the Classic Slum",
    "author": "Robert Roberts",
    "goodreadsId": "1185365",
    "dateAdded": "2023-07-12"
  },
  {
    "title": "Life at the Bottom: The Worldview That Makes the Underclass",
    "author": "Theodore Dalrymple",
    "goodreadsId": "117161",
    "dateAdded": "2023-07-12"
  },
  {
    "title": "The Classic Slum: Salford Life in the First Quarter of the Century",
    "author": "Robert Roberts",
    "goodreadsId": "567906",
    "dateAdded": "2023-07-12"
  },
  {
    "title": "Die andere Seite: Leben und Forschen zwischen New York und Berlin (German Edition)",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "61961187",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "Disenchanted Night: The Industrialization of Light in the Nineteenth Century",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "350025",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "In a Cold Crater: Cultural and Intellectual Life in Berlin, 1945-1948",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "350047",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "Tastes of Paradise",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "141602",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "The Making of an American Thinking Class: Intellectuals and Intelligentsia in Puritan Massachusetts",
    "author": "Darren M. Staloff",
    "goodreadsId": "1235601",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "The Railway Journey: The Industrialization of Time and Space in the 19th Century",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "918674",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "The War for Righteousness: Progressive Christianity, the Great War, and the Rise of the Messianic Nation",
    "author": "Richard M. Gamble",
    "goodreadsId": "1542479",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "Three New Deals: Reflections on Roosevelt's America, Mussolini's Italy, and Hitler's Germany, 1933-1939",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "350048",
    "dateAdded": "2023-07-10"
  },
  {
    "title": "American Education (Classic Reprint)",
    "author": "Sydney George Fisher",
    "goodreadsId": "31871548",
    "dateAdded": "2023-07-08"
  },
  {
    "title": "Chess Story",
    "author": "Stefan Zweig",
    "goodreadsId": "59151",
    "dateAdded": "2023-07-08"
  },
  {
    "title": "Crisis of Parliamentary Democracy (Studies in Contemporary German Social Thought)",
    "author": "Carl Schmitt",
    "goodreadsId": "279296",
    "dateAdded": "2023-07-08"
  },
  {
    "title": "The Gambler",
    "author": "Fyodor Dostoevsky",
    "goodreadsId": "12857",
    "dateAdded": "2023-07-08"
  },
  {
    "title": "THE STRUGGLE FOR AMERICAN INDEPENDENCE: VOLUMES I and II. (2 VOLUME SET)..",
    "author": "Sydney George Fisher",
    "goodreadsId": "163395600",
    "dateAdded": "2023-07-08"
  },
  {
    "title": "The True Benjamin Franklin",
    "author": "Sydney George Fisher",
    "goodreadsId": "13108827",
    "dateAdded": "2023-07-08"
  },
  {
    "title": "Leviathan and Its Enemies: Mass Organization and Managerial Power in Twentieth-Century America",
    "author": "Samuel T. Francis",
    "goodreadsId": "31571379",
    "dateAdded": "2023-07-05"
  },
  {
    "title": "Democracy and Liberty",
    "author": "William Edward Hartpole Lecky",
    "goodreadsId": "3510367",
    "dateAdded": "2023-07-04"
  },
  {
    "title": "History of European Morals: From Augustus To Charlemagne - Volume I",
    "author": "William Edward Hartpole Lecky",
    "goodreadsId": "3575769",
    "dateAdded": "2023-07-04"
  },
  {
    "title": "History of the Rise and Influence of the Spirit of Rationalism in Europe",
    "author": "William Edward Hartpole Lecky",
    "goodreadsId": "7858037",
    "dateAdded": "2023-07-04"
  },
  {
    "title": "The American Revolution, 1763-1783: Being The Chapters And Passages Relating To America From The Author's History Of England In The 18th Century",
    "author": "William Edward Hartpole Lecky",
    "goodreadsId": "2030212",
    "dateAdded": "2023-07-04"
  },
  {
    "title": "The Reconciliation of Government With Liberty",
    "author": "John William Burgess",
    "goodreadsId": "26650200",
    "dateAdded": "2023-07-04"
  },
  {
    "title": "Books vs Cigarettes",
    "author": "George Orwell",
    "goodreadsId": "61285888",
    "dateAdded": "2023-07-02"
  },
  {
    "title": "Theological-Political Treatise",
    "author": "Baruch Spinoza",
    "goodreadsId": "208657",
    "dateAdded": "2023-07-02"
  },
  {
    "title": "International Law",
    "author": "Henry James Sumner Maine",
    "goodreadsId": "11245286",
    "dateAdded": "2023-06-28"
  },
  {
    "title": "Lectures on the Early History of Institutions",
    "author": "Henry James Sumner Maine",
    "goodreadsId": "2966946",
    "dateAdded": "2023-06-28"
  },
  {
    "title": "Political Theology: Four Chapters on the Concept of Sovereignty",
    "author": "Carl Schmitt",
    "goodreadsId": "279246",
    "dateAdded": "2023-06-28"
  },
  {
    "title": "Popular Government",
    "author": "Henry James Sumner Maine",
    "goodreadsId": "4032296",
    "dateAdded": "2023-06-28"
  },
  {
    "title": "The English in the West Indies; or, The Bow of Ulysses",
    "author": "James Anthony Froude",
    "goodreadsId": "6291237",
    "dateAdded": "2023-06-28"
  },
  {
    "title": "Guide to Kulchur",
    "author": "Ezra Pound",
    "goodreadsId": "967411",
    "dateAdded": "2023-06-26"
  },
  {
    "title": "Stoner",
    "author": "John  Williams",
    "goodreadsId": "166997",
    "dateAdded": "2023-06-26"
  },
  {
    "title": "The Conquest of Gaul",
    "author": "Gaius Julius Caesar",
    "goodreadsId": "592167",
    "dateAdded": "2023-06-26"
  },
  {
    "title": "The Rise of Christianity",
    "author": "Rodney Stark",
    "goodreadsId": "30948",
    "dateAdded": "2023-06-26"
  },
  {
    "title": "The Structure of Politics at the Accession of George III",
    "author": "Lewis B. Namier",
    "goodreadsId": "1976308",
    "dateAdded": "2023-06-26"
  },
  {
    "title": "Scaling People: Tactics for Management and Company Building",
    "author": "Claire Hughes Johnson",
    "goodreadsId": "59744808",
    "dateAdded": "2023-06-22"
  },
  {
    "title": "Delirious New York: A Retroactive Manifesto for Manhattan",
    "author": "Rem Koolhaas",
    "goodreadsId": "118108",
    "dateAdded": "2023-06-19"
  },
  {
    "title": "The Law of Nations",
    "author": "Emer de Vattel",
    "goodreadsId": "4618391",
    "dateAdded": "2023-06-18"
  },
  {
    "title": "Blacklisted by History: The Untold Story of Senator Joe McCarthy and His Fight Against America's Enemies",
    "author": "M. Stanton Evans",
    "goodreadsId": "231155",
    "dateAdded": "2023-06-15"
  },
  {
    "title": "Democracy: The God That Failed",
    "author": "Hans-Hermann Hoppe",
    "goodreadsId": "980031",
    "dateAdded": "2023-06-15"
  },
  {
    "title": "Letter to a Child Never Born",
    "author": "Oriana Fallaci",
    "goodreadsId": "79429",
    "dateAdded": "2023-06-15"
  },
  {
    "title": "The Romance of American Communism",
    "author": "Vivian Gornick",
    "goodreadsId": "301758",
    "dateAdded": "2023-06-15"
  },
  {
    "title": "Private Power and American Democracy",
    "author": "Grant McConnell",
    "goodreadsId": "10502073",
    "dateAdded": "2023-05-30"
  },
  {
    "title": "The Mind of Napoleon: A Selection of His Written and Spoken Words",
    "author": "Napoléon Bonaparte",
    "goodreadsId": "1153633",
    "dateAdded": "2023-05-19"
  },
  {
    "title": "National System of Political Economy",
    "author": "Friedrich List",
    "goodreadsId": "7646170",
    "dateAdded": "2023-05-06"
  },
  {
    "title": "People's war: New light on the struggle for South Africa",
    "author": "Anthea Jeffery",
    "goodreadsId": "7712519",
    "dateAdded": "2023-05-06"
  },
  {
    "title": "Institutions, Institutional Change and Economic Performance",
    "author": "Douglass C. North",
    "goodreadsId": "741704",
    "dateAdded": "2023-05-02"
  },
  {
    "title": "The Rise of the Western World: A New Economic History",
    "author": "Douglass C. North",
    "goodreadsId": "335789",
    "dateAdded": "2023-05-02"
  },
  {
    "title": "Violence and Social Orders: A Conceptual Framework for Interpreting Recorded Human History",
    "author": "Douglass C. North",
    "goodreadsId": "5385951",
    "dateAdded": "2023-05-02"
  },
  {
    "title": "The Metamorphosis of Prime Intellect",
    "author": "Roger    Williams",
    "goodreadsId": "64341",
    "dateAdded": "2023-04-14"
  },
  {
    "title": "History of Economic Analysis",
    "author": "Joseph A. Schumpeter",
    "goodreadsId": "134800",
    "dateAdded": "2023-04-08"
  },
  {
    "title": "The Adventurous Heart: Figures and Capriccios",
    "author": "Ernst Jünger",
    "goodreadsId": "29927679",
    "dateAdded": "2023-03-16"
  },
  {
    "title": "NUTCRANKR",
    "author": "Dan Baltic",
    "goodreadsId": "91378850",
    "dateAdded": "2023-03-03"
  },
  {
    "title": "Diary of a Madman and Other Stories",
    "author": "Lu Xun",
    "goodreadsId": "127047",
    "dateAdded": "2023-02-08"
  },
  {
    "title": "The True Story of Ah Q",
    "author": "Lu Xun",
    "goodreadsId": "838938",
    "dateAdded": "2023-02-08"
  },
  {
    "title": "Economists and Societies: Discipline and Profession in the United States, Britain, and France, 1890s to 1990s (Princeton Studies in Cultural Sociology)",
    "author": "Marion Fourcade",
    "goodreadsId": "8763476",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "Empire of Silver: A New Monetary History of China",
    "author": "Jin Xu",
    "goodreadsId": "54849810",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "Fossil Future: Why Global Human Flourishing Requires More Oil, Coal, and Natural Gas--Not Less",
    "author": "Alex      Epstein",
    "goodreadsId": "58502699",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "Founders at Work: Stories of Startups' Early Days",
    "author": "Jessica Livingston",
    "goodreadsId": "98233",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "How to Write",
    "author": "Gertrude Stein",
    "goodreadsId": "778304",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "Public Choice Theory and the Illusion of Grand Strategy: How Generals, Weapons Manufacturers, and Foreign Governments Shape American Foreign Policy",
    "author": "Richard Hanania",
    "goodreadsId": "59858255",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "Thinking in Circles: An Essay on Ring Composition (The Terry Lectures Series)",
    "author": "Mary Douglas",
    "goodreadsId": "330385",
    "dateAdded": "2023-01-17"
  },
  {
    "title": "The Secret of Scent: Adventures in Perfume and the Science of Smell",
    "author": "Luca Turin",
    "goodreadsId": "14515",
    "dateAdded": "2023-01-15"
  },
  {
    "title": "Against Method",
    "author": "Paul Karl Feyerabend",
    "goodreadsId": "137979",
    "dateAdded": "2023-01-13"
  },
  {
    "title": "Farewell to Reason",
    "author": "Paul Karl Feyerabend",
    "goodreadsId": "147382",
    "dateAdded": "2023-01-13"
  },
  {
    "title": "Leviathan",
    "author": "Thomas Hobbes",
    "goodreadsId": "91953",
    "dateAdded": "2023-01-12"
  },
  {
    "title": "Music in the Galant Style",
    "author": "Robert Gjerdingen",
    "goodreadsId": "1955711",
    "dateAdded": "2023-01-11"
  },
  {
    "title": "Prometheus: The Life of Balzac",
    "author": "André Maurois",
    "goodreadsId": "159975",
    "dateAdded": "2023-01-06"
  },
  {
    "title": "No-No Boy (Classics of Asian American Literature)",
    "author": "John Okada",
    "goodreadsId": "129910",
    "dateAdded": "2023-01-04"
  },
  {
    "title": "Race War in High School, the Ten-Year Destruction of Franklin K. Lane High School in Brooklyn",
    "author": "Harold Saltzman",
    "goodreadsId": "5483438",
    "dateAdded": "2023-01-02"
  },
  {
    "title": "The Ladder of Success in Imperial China: Aspects of Social Mobility, 1368-1911",
    "author": "Ping-ti Ho",
    "goodreadsId": "5922070",
    "dateAdded": "2023-01-02"
  },
  {
    "title": "Suicide of the West: An Essay on the Meaning and Destiny of Liberalism",
    "author": "James Burnham",
    "goodreadsId": "1270376",
    "dateAdded": "2022-12-15"
  },
  {
    "title": "Libido Dominandi: Sexual Liberation and Political Control",
    "author": "E. Michael Jones",
    "goodreadsId": "1449354",
    "dateAdded": "2022-12-10"
  },
  {
    "title": "Div, Grad, Curl, and All That: An Informal Text on Vector Calculus",
    "author": "Harry M. Schey",
    "goodreadsId": "703104",
    "dateAdded": "2022-11-18"
  },
  {
    "title": "Dad's Nuke",
    "author": "Marc Laidlaw",
    "goodreadsId": "730945",
    "dateAdded": "2022-10-01"
  },
  {
    "title": "Novelist as a Vocation",
    "author": "Haruki Murakami",
    "goodreadsId": "60387307",
    "dateAdded": "2022-10-01"
  },
  {
    "title": "The Young Hitler I Knew",
    "author": "August Kubizek",
    "goodreadsId": "54276",
    "dateAdded": "2022-09-28"
  },
  {
    "title": "Storm of Steel",
    "author": "Ernst Jünger",
    "goodreadsId": "240485",
    "dateAdded": "2022-09-21"
  },
  {
    "title": "The History of Rome Vol. 1-5 (Annotated)",
    "author": "Theodor Mommsen",
    "goodreadsId": "18905184",
    "dateAdded": "2022-09-19"
  },
  {
    "title": "The Roman Revolution",
    "author": "Ronald Syme",
    "goodreadsId": "167913",
    "dateAdded": "2022-09-19"
  },
  {
    "title": "The Roman Triumph",
    "author": "Mary Beard",
    "goodreadsId": "1248750",
    "dateAdded": "2022-09-19"
  },
  {
    "title": "Odyssey Of A Liberal",
    "author": "Freda Utley",
    "goodreadsId": "13612925",
    "dateAdded": "2022-09-17"
  },
  {
    "title": "Sartor Resartus",
    "author": "Thomas Carlyle",
    "goodreadsId": "52998",
    "dateAdded": "2022-09-17"
  },
  {
    "title": "Assignment in Utopia",
    "author": "Eugene Lyons",
    "goodreadsId": "804216",
    "dateAdded": "2022-09-16"
  },
  {
    "title": "Background To Betrayal: The Tragedy Of Vietnam",
    "author": "Hilaire du Berrier",
    "goodreadsId": "8529729",
    "dateAdded": "2022-09-16"
  },
  {
    "title": "The Red Decade: The Stalinist Penetration of America",
    "author": "Eugene Lyons",
    "goodreadsId": "6275715",
    "dateAdded": "2022-09-16"
  },
  {
    "title": "Memoirs of a Superfluous Man",
    "author": "Albert Jay Nock",
    "goodreadsId": "84296",
    "dateAdded": "2022-09-15"
  },
  {
    "title": "Capitalism, Socialism and Democracy",
    "author": "Joseph A. Schumpeter",
    "goodreadsId": "134798",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "Great Wars And Great Leaders: A Libertarian Rebuttal",
    "author": "Ralph Raico",
    "goodreadsId": "9962512",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "Nation, State, and Economy: Contributions to the Politics and History of Our Time (Liberty Fund Library of the Works of Ludwig von Mises)",
    "author": "Ludwig von Mises",
    "goodreadsId": "264472",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "The Gift",
    "author": "Vladimir Nabokov",
    "goodreadsId": "8147",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "The Mystery of Banking",
    "author": "Murray N. Rothbard",
    "goodreadsId": "154253",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "The Progressive Era",
    "author": "Murray N. Rothbard",
    "goodreadsId": "36387450",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "The Sociology of Philosophies: A Global Theory of Intellectual Change",
    "author": "Randall Collins",
    "goodreadsId": "269724",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "What Is to Be Done?",
    "author": "Vladimir Lenin",
    "goodreadsId": "1108378",
    "dateAdded": "2022-09-14"
  },
  {
    "title": "America Goes to War",
    "author": "Charles Callan Tansill",
    "goodreadsId": "6342642",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "An Economic Interpretation of the Constitution of the United States",
    "author": "Charles A. Beard",
    "goodreadsId": "187702",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Aristocracy: A Very Short Introduction",
    "author": "William Doyle",
    "goodreadsId": "9066243",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Autism: A Very Short Introduction",
    "author": "Uta Frith",
    "goodreadsId": "6268135",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Catholicism: The Story of Catholic Christianity",
    "author": "Gerald O'Collins",
    "goodreadsId": "354865",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Design for war: A study of secret power politics 1937-1941",
    "author": "Frederic Rockwell Sanborn",
    "goodreadsId": "54233058",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Japanese Literature: A Very Short Introduction",
    "author": "Alan M. Tansman",
    "goodreadsId": "52617928",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Kabbalah: A Very Short Introduction",
    "author": "Joseph Dan",
    "goodreadsId": "3206523",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Napoleon: A Concise Biography",
    "author": "David A.  Bell",
    "goodreadsId": "26261382",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Poststructuralism: A Very Short Introduction",
    "author": "Catherine Belsey",
    "goodreadsId": "556041",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "President Roosevelt and the Coming of the War, 1941: A Study in Appearances and Realities",
    "author": "Charles A. Beard",
    "goodreadsId": "2020942",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Samurai: A Concise History",
    "author": "Michael Wert",
    "goodreadsId": "41551705",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Schizophrenia: A Very Short Introduction",
    "author": "Chris Frith",
    "goodreadsId": "452151",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The Cultural Revolution: A Very Short Introduction",
    "author": "Richard Curt Kraus",
    "goodreadsId": "11399999",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The First World War: A Very Short Introduction",
    "author": "Michael Eliot Howard",
    "goodreadsId": "25858",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The French Revolution: A Very Short Introduction",
    "author": "William Doyle",
    "goodreadsId": "318233",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The History of Childhood: A Very Short Introduction",
    "author": "James Marten",
    "goodreadsId": "38819243",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The Reformation: A Very Short Introduction",
    "author": "Peter        Marshall",
    "goodreadsId": "6934380",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The Roman Empire: A Very Short Introduction",
    "author": "Christopher     Kelly",
    "goodreadsId": "372557",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "The Russian Revolution: A Very Short Introduction",
    "author": "S.A.   Smith",
    "goodreadsId": "74652",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "World War II: A Very Short Introduction",
    "author": "Gerhard L. Weinberg",
    "goodreadsId": "22104318",
    "dateAdded": "2022-09-13"
  },
  {
    "title": "Reading Lolita in Tehran: A Memoir in Books",
    "author": "Azar Nafisi",
    "goodreadsId": "7603",
    "dateAdded": "2022-09-12"
  },
  {
    "title": "This Way for the Gas, Ladies and Gentlemen",
    "author": "Tadeusz Borowski",
    "goodreadsId": "228244",
    "dateAdded": "2022-09-12"
  },
  {
    "title": "Abraham Lincoln, 1809 1858 Volume 1",
    "author": "Albert J. Beveridge",
    "goodreadsId": "29724559",
    "dateAdded": "2022-09-11"
  },
  {
    "title": "The Culture of Defeat: On National Trauma, Mourning, and Recovery",
    "author": "Wolfgang Schivelbusch",
    "goodreadsId": "239728",
    "dateAdded": "2022-09-11"
  },
  {
    "title": "Capitalism with Chinese Characteristics: Entrepreneurship and the State",
    "author": "Yasheng Huang",
    "goodreadsId": "3421423",
    "dateAdded": "2022-09-09"
  },
  {
    "title": "A Secret History of Christianity: Jesus, The Last Inkling, And The Evolution Of Consciousness",
    "author": "Mark Vernon",
    "goodreadsId": "42789435",
    "dateAdded": "2022-09-08"
  },
  {
    "title": "Bureaucracy",
    "author": "Ludwig von Mises",
    "goodreadsId": "154409",
    "dateAdded": "2022-09-08"
  },
  {
    "title": "Conceived in Liberty Volumes I-IV",
    "author": "Murray N. Rothbard",
    "goodreadsId": "154251",
    "dateAdded": "2022-09-08"
  },
  {
    "title": "Human Action: A Treatise on Economics",
    "author": "Ludwig von Mises",
    "goodreadsId": "81912",
    "dateAdded": "2022-09-08"
  },
  {
    "title": "The Betrayal Of The American Right",
    "author": "Murray N. Rothbard",
    "goodreadsId": "1995212",
    "dateAdded": "2022-09-08"
  },
  {
    "title": "The Case Against the Fed",
    "author": "Murray N. Rothbard",
    "goodreadsId": "81976",
    "dateAdded": "2022-09-08"
  },
  {
    "title": "100 Multiple-Choice Questions",
    "author": "John Ashbery",
    "goodreadsId": "250402",
    "dateAdded": "2022-09-07"
  },
  {
    "title": "Gentle Art",
    "author": "Iphgenia Baal",
    "goodreadsId": "16694781",
    "dateAdded": "2022-09-07"
  },
  {
    "title": "Minima Moralia: Reflections on a Damaged Life",
    "author": "Theodor W. Adorno",
    "goodreadsId": "201388",
    "dateAdded": "2022-09-07"
  },
  {
    "title": "The Philosophy of History",
    "author": "Georg Wilhelm Friedrich Hegel",
    "goodreadsId": "25241",
    "dateAdded": "2022-09-07"
  },
  {
    "title": "The Future Is History: How Totalitarianism Reclaimed Russia",
    "author": "Masha Gessen",
    "goodreadsId": "34713325",
    "dateAdded": "2022-09-05"
  },
  {
    "title": "A Southside View Of Slavery: Or Three Months At The South, In 1854",
    "author": "Nehemiah Adams",
    "goodreadsId": "1839234",
    "dateAdded": "2022-09-04"
  },
  {
    "title": "Lincoln: The Man",
    "author": "Edgar Lee Masters",
    "goodreadsId": "1000250",
    "dateAdded": "2022-09-04"
  },
  {
    "title": "Mr. Buchanan's Administration On The Eve Of The Rebellion (1866)",
    "author": "James    Buchanan",
    "goodreadsId": "6800485",
    "dateAdded": "2022-09-04"
  },
  {
    "title": "Spoon River Anthology",
    "author": "Edgar Lee Masters",
    "goodreadsId": "292668",
    "dateAdded": "2022-09-04"
  },
  {
    "title": "Advance to Barbarism: The Development of Total Warfare from Sarajevo to Hiroshima",
    "author": "Frederick J. Veale",
    "goodreadsId": "1707241",
    "dateAdded": "2022-09-02"
  },
  {
    "title": "The Gray Notebook (New York Review Books Classics)",
    "author": "Josep Pla",
    "goodreadsId": "17316537",
    "dateAdded": "2022-09-02"
  },
  {
    "title": "A short History of Political Philosophy",
    "author": "Gaetano Mosca",
    "goodreadsId": "4693616",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "Enjoyment of Living",
    "author": "Max Eastman",
    "goodreadsId": "17256792",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "Fanaticism: On the Uses of an Idea",
    "author": "Alberto Toscano",
    "goodreadsId": "6529080",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "Patriarcha; or, the Natural Power of Kings",
    "author": "Robert Filmer",
    "goodreadsId": "25776985",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "Strange Defeat",
    "author": "Marc Bloch",
    "goodreadsId": "152476",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "The Concept of the Political",
    "author": "Carl Schmitt",
    "goodreadsId": "279245",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "The Origins of Totalitarianism",
    "author": "Hannah Arendt",
    "goodreadsId": "396931",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "The Ruling Class",
    "author": "Gaetano Mosca",
    "goodreadsId": "1461876",
    "dateAdded": "2022-09-01"
  },
  {
    "title": "Peter Oliver's Origin and Progress of the American Rebellion: A Tory View",
    "author": "Peter Oliver",
    "goodreadsId": "1524989",
    "dateAdded": "2022-08-29"
  },
  {
    "title": "The Gingerbread Race: A Life in the Closing World Once Called Free",
    "author": "Andrei Navrozov",
    "goodreadsId": "5755422",
    "dateAdded": "2022-08-29"
  },
  {
    "title": "The Origin of the Late War",
    "author": "George Lunt",
    "goodreadsId": "10158773",
    "dateAdded": "2022-08-29"
  },
  {
    "title": "The Professor of Desire",
    "author": "Philip Roth",
    "goodreadsId": "29743",
    "dateAdded": "2022-08-25"
  },
  {
    "title": "The Piano Teacher",
    "author": "Elfriede Jelinek",
    "goodreadsId": "219879",
    "dateAdded": "2022-08-18"
  },
  {
    "title": "Tropic of Cancer (Tropic, #1)",
    "author": "Henry Miller",
    "goodreadsId": "249",
    "dateAdded": "2022-08-18"
  },
  {
    "title": "Gauguin's Paradise Lost",
    "author": "Wayne V. Andersen",
    "goodreadsId": "5289262",
    "dateAdded": "2022-08-16"
  },
  {
    "title": "Cartesian Sonata and Other Novellas",
    "author": "William H. Gass",
    "goodreadsId": "156183",
    "dateAdded": "2022-08-13"
  },
  {
    "title": "Woodcutters",
    "author": "Thomas Bernhard",
    "goodreadsId": "92576",
    "dateAdded": "2022-08-11"
  },
  {
    "title": "Life Studies",
    "author": "Robert Lowell",
    "goodreadsId": "385580",
    "dateAdded": "2022-07-29"
  },
  {
    "title": "The Pale King",
    "author": "David Foster Wallace",
    "goodreadsId": "9443405",
    "dateAdded": "2022-07-27"
  },
  {
    "title": "Paintings in Proust: A Visual Companion to 'In Search of Lost Time'",
    "author": "Eric Karpeles",
    "goodreadsId": "3753149",
    "dateAdded": "2022-07-18"
  },
  {
    "title": "EarthBound (Boss Fight Books, #1)",
    "author": "Ken Baumann",
    "goodreadsId": "19386071",
    "dateAdded": "2022-07-17"
  },
  {
    "title": "Postscript on the Societies of Control",
    "author": "Gilles Deleuze",
    "goodreadsId": "19499462",
    "dateAdded": "2022-07-17"
  },
  {
    "title": "Law in Everyday Japan: Sex, Sumo, Suicide, and Statutes",
    "author": "Mark D. West",
    "goodreadsId": "500108",
    "dateAdded": "2022-07-15"
  },
  {
    "title": "Andrew Kuo: What Me Worry",
    "author": "Kelefa Sanneh",
    "goodreadsId": "9843506",
    "dateAdded": "2022-07-13"
  },
  {
    "title": "Atlanta: Hip-Hop and the South",
    "author": "Michael Schmelling",
    "goodreadsId": "8737053",
    "dateAdded": "2022-07-13"
  },
  {
    "title": "Major Labels: A History of Popular Music in Seven Genres",
    "author": "Kelefa Sanneh",
    "goodreadsId": "56912932",
    "dateAdded": "2022-07-13"
  },
  {
    "title": "The Unincorporated Man  (Unincorporated Man, #1)",
    "author": "Dani Kollin",
    "goodreadsId": "4025200",
    "dateAdded": "2022-07-11"
  },
  {
    "title": "Boy in the Twilight: Stories of the Hidden China",
    "author": "Yu Hua",
    "goodreadsId": "17857635",
    "dateAdded": "2022-07-10"
  },
  {
    "title": "China in Ten Words",
    "author": "Yu Hua",
    "goodreadsId": "12884314",
    "dateAdded": "2022-07-10"
  },
  {
    "title": "Chronicle of a Blood Merchant",
    "author": "Yu Hua",
    "goodreadsId": "334970",
    "dateAdded": "2022-07-10"
  },
  {
    "title": "The Seventh Day",
    "author": "Yu Hua",
    "goodreadsId": "22107229",
    "dateAdded": "2022-07-10"
  },
  {
    "title": "To Live",
    "author": "Yu Hua",
    "goodreadsId": "334971",
    "dateAdded": "2022-07-10"
  },
  {
    "title": "Who Are We?: The Challenges to America's National Identity",
    "author": "Samuel P. Huntington",
    "goodreadsId": "209178",
    "dateAdded": "2022-07-05"
  },
  {
    "title": "Kabbalah",
    "author": "Gershom Scholem",
    "goodreadsId": "1150775",
    "dateAdded": "2022-06-27"
  },
  {
    "title": "On the Kabbalah and its Symbolism",
    "author": "Gershom Scholem",
    "goodreadsId": "343902",
    "dateAdded": "2022-06-27"
  },
  {
    "title": "Sabbatai Sevi: The Mystical Messiah, 1626-1676",
    "author": "Gershom Scholem",
    "goodreadsId": "343903",
    "dateAdded": "2022-06-27"
  },
  {
    "title": "The Anathemata: Fragments of an Attempted Writing",
    "author": "David  Jones",
    "goodreadsId": "1762157",
    "dateAdded": "2022-06-27"
  },
  {
    "title": "Zohar: The Book of Splendor: Basic Readings from the Kabbalah",
    "author": "Gershom Scholem",
    "goodreadsId": "674355",
    "dateAdded": "2022-06-27"
  },
  {
    "title": "A Deepness in the Sky (Zones of Thought, #2)",
    "author": "Vernor Vinge",
    "goodreadsId": "226004",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "Erotism: Death and Sensuality",
    "author": "Georges Bataille",
    "goodreadsId": "37530",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "Inner Experience",
    "author": "Georges Bataille",
    "goodreadsId": "437771",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "Novels By Vernor Vinge (Study Guide): A Fire Upon The Deep, A Deepness In The Sky, Rainbows End, Marooned In Realtime, The Cookie Monster",
    "author": "Books LLC",
    "goodreadsId": "9796189",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "On Nietzsche",
    "author": "Georges Bataille",
    "goodreadsId": "437780",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "The Accursed Share: An Essay on General Economy, Volume I: Consumption",
    "author": "Georges Bataille",
    "goodreadsId": "350003",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "The Founders: The Story of Paypal and the Entrepreneurs Who Shaped Silicon Valley",
    "author": "Jimmy Soni",
    "goodreadsId": "54304287",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "The Power Law: Venture Capital and the Making of the New Future",
    "author": "Sebastian Mallaby",
    "goodreadsId": "58009109",
    "dateAdded": "2022-06-26"
  },
  {
    "title": "A New Theory of Urban Design (Center for Environmental Structure Series)",
    "author": "Christopher W. Alexander",
    "goodreadsId": "106727",
    "dateAdded": "2022-06-24"
  },
  {
    "title": "Centuries of Meditations",
    "author": "Thomas Traherne",
    "goodreadsId": "1605898",
    "dateAdded": "2022-06-24"
  },
  {
    "title": "In Parenthesis",
    "author": "David  Jones",
    "goodreadsId": "428945",
    "dateAdded": "2022-06-24"
  },
  {
    "title": "Notes on the Synthesis of Form",
    "author": "Christopher W. Alexander",
    "goodreadsId": "320553",
    "dateAdded": "2022-06-24"
  },
  {
    "title": "Shop Class as Soulcraft: An Inquiry Into the Value of Work",
    "author": "Matthew B. Crawford",
    "goodreadsId": "6261332",
    "dateAdded": "2022-06-24"
  },
  {
    "title": "The Last Puritan: A Memoir in the Form of a Novel",
    "author": "George Santayana",
    "goodreadsId": "403281",
    "dateAdded": "2022-06-24"
  },
  {
    "title": "Emergent Tokyo: Designing the Spontaneous City",
    "author": "Jorge Almazán",
    "goodreadsId": "61097667",
    "dateAdded": "2022-06-15"
  },
  {
    "title": "The Cuckoo's Egg: Tracking a Spy Through the Maze of Computer Espionage",
    "author": "Clifford Stoll",
    "goodreadsId": "18154",
    "dateAdded": "2022-06-15"
  },
  {
    "title": "The Making of Urban Japan: Cities and Planning from Edo to the Twenty First Century",
    "author": "André Sorensen",
    "goodreadsId": "390157",
    "dateAdded": "2022-06-15"
  },
  {
    "title": "Paul Rand: A Designer's Art",
    "author": "Paul Rand",
    "goodreadsId": "163436",
    "dateAdded": "2022-06-12"
  },
  {
    "title": "Unknown Market Wizards: The Best Traders You've Never Heard of (Market Wizards, #5)",
    "author": "Jack D. Schwager",
    "goodreadsId": "54308357",
    "dateAdded": "2022-06-12"
  },
  {
    "title": "A Secular Age",
    "author": "Charles Margrave Taylor",
    "goodreadsId": "824412",
    "dateAdded": "2022-06-04"
  },
  {
    "title": "Linear Algebra Done Right (Undergraduate Texts in Mathematics)",
    "author": "Sheldon Axler",
    "goodreadsId": "309768",
    "dateAdded": "2022-06-04"
  },
  {
    "title": "Sources of the Self: The Making of the Modern Identity",
    "author": "Charles Margrave Taylor",
    "goodreadsId": "37858",
    "dateAdded": "2022-06-04"
  },
  {
    "title": "VALIS",
    "author": "Philip K. Dick",
    "goodreadsId": "216377",
    "dateAdded": "2022-06-04"
  },
  {
    "title": "The Black Hunter: Forms of Thought and Forms of Society in the Greek World",
    "author": "Pierre Vidal-Naquet",
    "goodreadsId": "407634",
    "dateAdded": "2022-06-01"
  },
  {
    "title": "Lying for Money: How Legendary Frauds Reveal the Workings of Our World",
    "author": "Dan Davies",
    "goodreadsId": "38605195",
    "dateAdded": "2022-05-28"
  },
  {
    "title": "The Last Days of Hitler",
    "author": "Hugh Trevor-Roper",
    "goodreadsId": "945011",
    "dateAdded": "2022-05-22"
  },
  {
    "title": "A Confederacy of Dunces",
    "author": "John Kennedy Toole",
    "goodreadsId": "310612",
    "dateAdded": "2022-05-21"
  },
  {
    "title": "Bringing Down the House: The Inside Story of Six M.I.T. Students Who Took Vegas for Millions",
    "author": "Ben Mezrich",
    "goodreadsId": "514313",
    "dateAdded": "2022-05-14"
  },
  {
    "title": "Rip It Up",
    "author": "Kou Machida",
    "goodreadsId": "59978061",
    "dateAdded": "2022-05-14"
  },
  {
    "title": "Bibliomania",
    "author": "Gustave Flaubert",
    "goodreadsId": "3451537",
    "dateAdded": "2022-05-11"
  },
  {
    "title": "Memoirs of a Madman",
    "author": "Gustave Flaubert",
    "goodreadsId": "60698",
    "dateAdded": "2022-05-11"
  },
  {
    "title": "November",
    "author": "Gustave Flaubert",
    "goodreadsId": "125324",
    "dateAdded": "2022-05-11"
  },
  {
    "title": "Confessions of an English Opium Eater",
    "author": "Thomas de Quincey",
    "goodreadsId": "87635",
    "dateAdded": "2022-05-10"
  },
  {
    "title": "For Self-Examination/Judge for Yourself!",
    "author": "Søren Kierkegaard",
    "goodreadsId": "242007",
    "dateAdded": "2022-05-06"
  },
  {
    "title": "The Concept of Irony: With Continual Reference to Socrates/Notes of Schelling's Berlin Lectures",
    "author": "Søren Kierkegaard",
    "goodreadsId": "99290",
    "dateAdded": "2022-05-06"
  },
  {
    "title": "The Seducer’s Diary",
    "author": "Søren Kierkegaard",
    "goodreadsId": "46973",
    "dateAdded": "2022-05-06"
  },
  {
    "title": "Dutch: A Memoir of Ronald Reagan",
    "author": "Edmund  Morris",
    "goodreadsId": "376589",
    "dateAdded": "2022-05-05"
  },
  {
    "title": "Fairy Tales from the Brothers Grimm: A New English Version",
    "author": "Philip Pullman",
    "goodreadsId": "13554713",
    "dateAdded": "2022-05-05"
  },
  {
    "title": "Look Here: On the Pleasures of Observing the City",
    "author": "Ana Kinsella",
    "goodreadsId": "60045211",
    "dateAdded": "2022-05-05"
  },
  {
    "title": "The Rise of Theodore Roosevelt (Theodore Roosevelt, #1)",
    "author": "Edmund  Morris",
    "goodreadsId": "40929",
    "dateAdded": "2022-05-05"
  },
  {
    "title": "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
    "author": "Ashlee Vance",
    "goodreadsId": "25541028",
    "dateAdded": "2022-04-29"
  },
  {
    "title": "Business Cycles and Equilibrium",
    "author": "Fischer Black",
    "goodreadsId": "7041875",
    "dateAdded": "2022-04-24"
  },
  {
    "title": "Exploring General Equilibrium",
    "author": "Fischer Black",
    "goodreadsId": "1069380",
    "dateAdded": "2022-04-24"
  },
  {
    "title": "The Confusions of Young Törless",
    "author": "Robert Musil",
    "goodreadsId": "18289304",
    "dateAdded": "2022-04-17"
  },
  {
    "title": "The Life and Opinions of the Tomcat Murr",
    "author": "E.T.A. Hoffmann",
    "goodreadsId": "594852",
    "dateAdded": "2022-04-15"
  },
  {
    "title": "The Life and Opinions of Tristram Shandy, Gentleman",
    "author": "Laurence Sterne",
    "goodreadsId": "76527",
    "dateAdded": "2022-04-15"
  },
  {
    "title": "The Quilt and Other Stories by Tayama Katai (English and Japanese Edition)",
    "author": "Katai Tayama",
    "goodreadsId": "930916",
    "dateAdded": "2022-04-15"
  },
  {
    "title": "Beethoven for a Later Age: The Journey of a String Quartet",
    "author": "Edward Dusinberre",
    "goodreadsId": "28664560",
    "dateAdded": "2022-04-10"
  },
  {
    "title": "Beethoven's Conversation Books Volume 1: Nos. 1 to 8 (February 1818 to March 1820)",
    "author": "Theodore Albrecht",
    "goodreadsId": "29737338",
    "dateAdded": "2022-04-09"
  },
  {
    "title": "Investing Amid Low Expected Returns: Making the Most When Markets Offer the Least",
    "author": "Antti Ilmanen",
    "goodreadsId": "59792176",
    "dateAdded": "2022-04-09"
  },
  {
    "title": "Johann Sebastian Bach: The Learned Musician",
    "author": "Christoph Wolff",
    "goodreadsId": "79644",
    "dateAdded": "2022-04-09"
  },
  {
    "title": "The True History of the American Revolution",
    "author": "Sydney George Fisher",
    "goodreadsId": "25843585",
    "dateAdded": "2022-04-07"
  },
  {
    "title": "Diaries, 1910-1923",
    "author": "Franz Kafka",
    "goodreadsId": "17686",
    "dateAdded": "2022-04-06"
  },
  {
    "title": "Eumeswil",
    "author": "Ernst Jünger",
    "goodreadsId": "506145",
    "dateAdded": "2022-04-06"
  },
  {
    "title": "Hitler's Table Talk, 1941-1944",
    "author": "Norman Cameron",
    "goodreadsId": "54332",
    "dateAdded": "2022-04-06"
  },
  {
    "title": "Origins of the Popular Style: The Antecedents of Twentieth-Century Popular Music (Clarendon Paperbacks)",
    "author": "Peter Van Der Merwe",
    "goodreadsId": "1140868",
    "dateAdded": "2022-04-06"
  },
  {
    "title": "Roots of the Classical: The Popular Origins of Western Music",
    "author": "Peter Van Der Merwe",
    "goodreadsId": "3003213",
    "dateAdded": "2022-04-06"
  },
  {
    "title": "Stubborn Attachments: A Vision for a Society of Free, Prosperous, and Responsible Individuals",
    "author": "Tyler Cowen",
    "goodreadsId": "31283667",
    "dateAdded": "2022-04-05"
  },
  {
    "title": "The Journey of Humanity: The Origins of Wealth and Inequality",
    "author": "Oded Galor",
    "goodreadsId": "58502650",
    "dateAdded": "2022-03-04"
  },
  {
    "title": "The Routledge Handbook of the Economics of Education (Routledge International Handbooks)",
    "author": "Brian P McCall",
    "goodreadsId": "58445735",
    "dateAdded": "2022-03-04"
  },
  {
    "title": "Unified Growth Theory",
    "author": "Oded Galor",
    "goodreadsId": "11332457",
    "dateAdded": "2022-03-04"
  },
  {
    "title": "Artificial Intelligence: A Guide for Thinking Humans",
    "author": "Melanie  Mitchell",
    "goodreadsId": "43565360",
    "dateAdded": "2022-03-02"
  },
  {
    "title": "How to Invent Everything: A Survival Guide for the Stranded Time Traveler",
    "author": "Ryan North",
    "goodreadsId": "39026990",
    "dateAdded": "2022-03-02"
  },
  {
    "title": "In Defense of Elitism: Why I'm Better Than You and You are Better Than Someone Who Didn't Buy This Book",
    "author": "Joel Stein",
    "goodreadsId": "43885900",
    "dateAdded": "2022-03-02"
  },
  {
    "title": "Metaphors We Live By",
    "author": "George Lakoff",
    "goodreadsId": "34459",
    "dateAdded": "2022-03-02"
  },
  {
    "title": "The Northern Caves",
    "author": "nostalgebraist",
    "goodreadsId": "25503770",
    "dateAdded": "2022-02-16"
  },
  {
    "title": "Lost in the Cosmos: The Last Self-Help Book",
    "author": "Walker Percy",
    "goodreadsId": "77959",
    "dateAdded": "2022-02-11"
  },
  {
    "title": "Rabbit, Run (Rabbit Angstrom, #1)",
    "author": "John Updike",
    "goodreadsId": "40656712",
    "dateAdded": "2022-02-11"
  },
  {
    "title": "The Dictator's Handbook: Why Bad Behavior Is Almost Always Good Politics",
    "author": "Bruce Bueno de Mesquita",
    "goodreadsId": "11612989",
    "dateAdded": "2022-02-09"
  },
  {
    "title": "A World at Arms: A Global History of World War II",
    "author": "Gerhard L. Weinberg",
    "goodreadsId": "302022",
    "dateAdded": "2022-02-06"
  },
  {
    "title": "Brain of the Firm (Classic Beer Series)",
    "author": "Stafford Beer",
    "goodreadsId": "1304488",
    "dateAdded": "2022-02-06"
  },
  {
    "title": "Identity, Consciousness and Value",
    "author": "Peter K. Unger",
    "goodreadsId": "83375",
    "dateAdded": "2022-02-03"
  },
  {
    "title": "Ignorance: A Case for Scepticism (Clarendon Library of Logic and Philosophy)",
    "author": "Peter K. Unger",
    "goodreadsId": "83371",
    "dateAdded": "2022-02-03"
  },
  {
    "title": "Living High and Letting Die: Our Illusion of Innocence",
    "author": "Peter K. Unger",
    "goodreadsId": "1139000",
    "dateAdded": "2022-02-03"
  },
  {
    "title": "Talent: How to Identify Energizers, Creatives, and Winners Around the World",
    "author": "Tyler Cowen",
    "goodreadsId": "56269174",
    "dateAdded": "2022-02-03"
  },
  {
    "title": "A Pattern Language: Towns, Buildings, Construction (Center for Environmental Structure Series)",
    "author": "Christopher W. Alexander",
    "goodreadsId": "79766",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The City in History: Its Origins, Its Transformations, and Its Prospects",
    "author": "Lewis Mumford",
    "goodreadsId": "544053",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The City: A Global History (Modern Library Chronicles)",
    "author": "Joel Kotkin",
    "goodreadsId": "80854",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The Moviegoer",
    "author": "Walker Percy",
    "goodreadsId": "10739",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The Ordeal of Change",
    "author": "Eric Hoffer",
    "goodreadsId": "654107",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The Order of Things: An Archaeology of the Human Sciences",
    "author": "Michel Foucault",
    "goodreadsId": "119561",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The Timeless Way of Building",
    "author": "Christopher W. Alexander",
    "goodreadsId": "106728",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The True Believer: Thoughts on the Nature of Mass Movements",
    "author": "Eric Hoffer",
    "goodreadsId": "15916",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "Towards a New Architecture",
    "author": "Le Corbusier",
    "goodreadsId": "70134",
    "dateAdded": "2022-02-02"
  },
  {
    "title": "The Electric Kool-Aid Acid Test",
    "author": "Tom Wolfe",
    "goodreadsId": "7442",
    "dateAdded": "2022-01-25"
  },
  {
    "title": "The Singularity is Near: When Humans Transcend Biology",
    "author": "Ray Kurzweil",
    "goodreadsId": "83518",
    "dateAdded": "2022-01-21"
  },
  {
    "title": "Autobiography of Thomas Jefferson",
    "author": "Thomas Jefferson",
    "goodreadsId": "38775",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Belt and Road: A Chinese World Order",
    "author": "Bruno Maçães",
    "goodreadsId": "41213288",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Friends for 350 years",
    "author": "Howard H. Brinton",
    "goodreadsId": "30968308",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Hard-Boiled Wonderland and the End of the World",
    "author": "Haruki Murakami",
    "goodreadsId": "10374",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "History Has Begun",
    "author": "Bruno Maçães",
    "goodreadsId": "52914599",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Introduction to Modern Economic Growth",
    "author": "Daron Acemoğlu",
    "goodreadsId": "6766763",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Jefferson and the Rights of Man",
    "author": "Dumas Malone",
    "goodreadsId": "1532332",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Jefferson the Virginian",
    "author": "Dumas Malone",
    "goodreadsId": "826698",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Là-Bas (Down There)",
    "author": "Joris-Karl Huysmans",
    "goodreadsId": "315298",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Leonardo da Vinci",
    "author": "Walter Isaacson",
    "goodreadsId": "34684622",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Marie or, Slavery in the United States: A Novel of Jacksonian America (Race in the Americas)",
    "author": "Gustave Auguste de Beaumont",
    "goodreadsId": "532715",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Marthe: The Story of a Whore",
    "author": "Joris-Karl Huysmans",
    "goodreadsId": "210264",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Microeconomic Foundations I: Choice and Competitive Markets",
    "author": "David M. Kreps",
    "goodreadsId": "14891894",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Microeconomic Theory",
    "author": "Andreu Mas-Colell",
    "goodreadsId": "735963",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "The Dawn of Eurasia: On the Trail of the New World Order",
    "author": "Bruno Maçães",
    "goodreadsId": "34889281",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "The Immortality Key: Uncovering the Secret History of the Religion with No Name",
    "author": "Brian C. Muraresku",
    "goodreadsId": "51174256",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "The Journal Of John Woolman",
    "author": "John Woolman",
    "goodreadsId": "1426266",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "The Road to Eleusis: Unveiling the Secret of the Mysteries",
    "author": "R. Gordon Wasson",
    "goodreadsId": "2402353",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Which Country Has the World's Best Health Care?",
    "author": "Ezekiel J. Emanuel",
    "goodreadsId": "50262535",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "Why Nations Fail: The Origins of Power, Prosperity, and Poverty",
    "author": "Daron Acemoğlu",
    "goodreadsId": "12158480",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "With the Flow",
    "author": "Joris-Karl Huysmans",
    "goodreadsId": "210262",
    "dateAdded": "2022-01-19"
  },
  {
    "title": "A Simple Heart",
    "author": "Gustave Flaubert",
    "goodreadsId": "269894",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "Bouvard and Pécuchet",
    "author": "Gustave Flaubert",
    "goodreadsId": "40763",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "Crying in H Mart",
    "author": "Michelle Zauner",
    "goodreadsId": "54814676",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "Moby-Dick or, The Whale",
    "author": "Herman Melville",
    "goodreadsId": "153747",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "Sadly, Porn",
    "author": "Edward Teach",
    "goodreadsId": "59989719",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "The Dictionary of Accepted Ideas",
    "author": "Gustave Flaubert",
    "goodreadsId": "2185",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "The Man Without Qualities",
    "author": "Robert Musil",
    "goodreadsId": "527756",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "The Musil Diaries: Robert Musil, 1899-1942",
    "author": "Robert Musil",
    "goodreadsId": "191948",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "The Temptation of St. Antony",
    "author": "Gustave Flaubert",
    "goodreadsId": "355034",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "Three Tales",
    "author": "Gustave Flaubert",
    "goodreadsId": "2182",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "Watch What You Hear: Penelope's Dream Of Twenty Geese",
    "author": "Edward Teach",
    "goodreadsId": "54649415",
    "dateAdded": "2022-01-18"
  },
  {
    "title": "A Tokyo Romance",
    "author": "Ian Buruma",
    "goodreadsId": "35749434",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Behind the Mask: On Sexual Demons, Sacred Mothers, Transvestites, Gangsters, Drifters and other Japanese Cultural Heroes",
    "author": "Ian Buruma",
    "goodreadsId": "428197",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Beyond Order: 12 More Rules For Life",
    "author": "Jordan B. Peterson",
    "goodreadsId": "56019043",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "City of God",
    "author": "Augustine of Hippo",
    "goodreadsId": "25673",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Democracy in America",
    "author": "Alexis de Tocqueville",
    "goodreadsId": "16619",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Diary of a Short-Sighted Adolescent",
    "author": "Mircea Eliade",
    "goodreadsId": "28462485",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Embracing Defeat: Japan in the Wake of World War II",
    "author": "John W. Dower",
    "goodreadsId": "273197",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Fathers and Sons",
    "author": "Ivan Turgenev",
    "goodreadsId": "434286",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Interpreting the French Revolution",
    "author": "Elborg Forster",
    "goodreadsId": "687328",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Inventing Japan: 1853-1964",
    "author": "Ian Buruma",
    "goodreadsId": "251348",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Japan Rising: The Iwakura Embassy to the USA and Europe",
    "author": "Kume Kunitake",
    "goodreadsId": "10783154",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Nietzsche",
    "author": "Lou Andreas-Salomé",
    "goodreadsId": "70190",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "One Hundred Years of Solitude",
    "author": "Gabriel García Márquez",
    "goodreadsId": "18901575",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Revolutionary France 1770 - 1880 (History of France)",
    "author": "François Furet",
    "goodreadsId": "1148329",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "The Corrections",
    "author": "Jonathan Franzen",
    "goodreadsId": "15993",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "The Fall of the Roman Republic",
    "author": "Plutarch",
    "goodreadsId": "55002",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "The History of the Decline and Fall of the Roman Empire Volume I",
    "author": "Edward Gibbon",
    "goodreadsId": "377965",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "The Old Regime and the French Revolution",
    "author": "Alexis de Tocqueville",
    "goodreadsId": "448781",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "The Power Broker: Robert Moses and the Fall of New York",
    "author": "Robert A. Caro",
    "goodreadsId": "1111",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "The Universal Baseball Association, Inc., J. Henry Waugh, Prop.",
    "author": "Robert Coover",
    "goodreadsId": "156192",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Things Hidden Since the Foundation of the World",
    "author": "René Girard",
    "goodreadsId": "337517",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Three Novels: Molloy / Malone Dies / The Unnamable",
    "author": "Samuel Beckett",
    "goodreadsId": "5776903",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "Twelve Who Ruled: The Year of the Terror in the French Revolution",
    "author": "R.R. Palmer",
    "goodreadsId": "196977",
    "dateAdded": "2022-01-17"
  },
  {
    "title": "3:16 Bible Texts Illuminated",
    "author": "Donald Ervin Knuth",
    "goodreadsId": "112240",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "Beyond Culture",
    "author": "Edward T. Hall",
    "goodreadsId": "251347",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "Creative Destruction: How Globalization Is Changing the World's Cultures",
    "author": "Tyler Cowen",
    "goodreadsId": "117125",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "Discover Your Inner Economist: Use Incentives to Fall in Love, Survive Your Next Meeting, and Motivate Your Dentist",
    "author": "Tyler Cowen",
    "goodreadsId": "700668",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "In Praise of Commercial Culture",
    "author": "Tyler Cowen",
    "goodreadsId": "117137",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "Indiscrete Thoughts",
    "author": "Fabrizio Palombi Gian-Carlo Rota",
    "goodreadsId": "1646354",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "The Red Queen: Sex and the Evolution of Human Nature",
    "author": "Matt Ridley",
    "goodreadsId": "16176",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "Things a Computer Scientist Rarely Talks About (Volume 136) (Lecture Notes)",
    "author": "Donald Ervin Knuth",
    "goodreadsId": "484459",
    "dateAdded": "2022-01-16"
  },
  {
    "title": "The Complete Short Novels",
    "author": "Anton Chekhov",
    "goodreadsId": "5697",
    "dateAdded": "2020-01-07"
  },
  {
    "title": "In Praise of Shadows",
    "author": "Jun'ichirō Tanizaki",
    "goodreadsId": "34473",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "Naomi",
    "author": "Jun'ichirō Tanizaki",
    "goodreadsId": "34462",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "Some Prefer Nettles",
    "author": "Jun'ichirō Tanizaki",
    "goodreadsId": "194642",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "The Brothers Karamazov",
    "author": "Fyodor Dostoevsky",
    "goodreadsId": "4934",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "The Double and The Gambler",
    "author": "Fyodor Dostoevsky",
    "goodreadsId": "5698",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "The Little Prince & Letter to a Hostage",
    "author": "Antoine de Saint-Exupéry",
    "goodreadsId": "3241368",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "The Sound and the Fury",
    "author": "William Faulkner",
    "goodreadsId": "10975",
    "dateAdded": "2020-01-06"
  },
  {
    "title": "Asleep",
    "author": "Banana Yoshimoto",
    "goodreadsId": "50143",
    "dateAdded": "2017-07-13"
  },
  {
    "title": "Buddenbrooks: The Decline of a Family",
    "author": "Thomas Mann",
    "goodreadsId": "80890",
    "dateAdded": "2014-12-24"
  }
];
