const tvItems = [
  {
    "id": "tvmaze-44933",
    "tvmaze_id": 44933,
    "title": "Severance",
    "cover": "images/covers/tv-44933.jpg",
    "tvmaze_url": "https://www.tvmaze.com/shows/44933/severance",
    "format": "Scripted",
    "language": "English",
    "network": "Apple TV",
    "episodes": 19,
    "runtime_minutes": 49,
    "total_minutes": 927,
    "hours": 15.5,
    "premiered": "2022-02-18",
    "ended": "",
    "date_completed": "2022-05-05",
    "source_index": 0
  },
  {
    "id": "tvmaze-2761",
    "tvmaze_id": 2761,
    "title": "Master of None",
    "cover": "images/covers/tv-2761.jpg",
    "tvmaze_url": "https://www.tvmaze.com/shows/2761/master-of-none",
    "format": "Scripted",
    "language": "English",
    "network": "Netflix",
    "episodes": 25,
    "runtime_minutes": 32,
    "total_minutes": 805,
    "hours": 13.4,
    "premiered": "2015-11-06",
    "ended": "2021-05-23",
    "date_completed": "2017-05-25",
    "source_index": 1
  },
  {
    "id": "tvmaze-82",
    "tvmaze_id": 82,
    "title": "Game of Thrones",
    "cover": "images/covers/tv-82.jpg",
    "tvmaze_url": "https://www.tvmaze.com/shows/82/game-of-thrones",
    "format": "Scripted",
    "language": "English",
    "network": "HBO",
    "episodes": 73,
    "runtime_minutes": 61,
    "total_minutes": 4476,
    "hours": 74.6,
    "premiered": "2011-04-17",
    "ended": "2019-05-19",
    "date_completed": "2016-12-05",
    "source_index": 2
  },
  {
    "id": "tvmaze-342",
    "tvmaze_id": 342,
    "title": "Louie",
    "cover": "images/covers/tv-342.jpg",
    "tvmaze_url": "https://www.tvmaze.com/shows/342/louie",
    "format": "Scripted",
    "language": "English",
    "network": "FX",
    "episodes": 61,
    "runtime_minutes": 30,
    "total_minutes": 1830,
    "hours": 30.5,
    "premiered": "2010-06-29",
    "ended": "2015-05-28",
    "date_completed": "2016-03-12",
    "source_index": 3
  },
  {
    "id": "tvmaze-169",
    "tvmaze_id": 169,
    "title": "Breaking Bad",
    "cover": "images/covers/tv-169.jpg",
    "tvmaze_url": "https://www.tvmaze.com/shows/169/breaking-bad",
    "format": "Scripted",
    "language": "English",
    "network": "AMC",
    "episodes": 62,
    "runtime_minutes": 60,
    "total_minutes": 3720,
    "hours": 62,
    "premiered": "2008-01-20",
    "ended": "2019-10-11",
    "date_completed": "2014-12-04",
    "source_index": 4
  }
];
